### ISSUE TITLE
Something went wrong while downloading

### ISSUE THREAD

**Issue by wsc96** [deepjyoti30/ytmdl#10]
I get the below message whenever attempting to run ytmdl regardless of whether I supply the URL or just the song name.

 ==> Something went wrong while downloading!

The version I have is v0.2-r4.

Is there a log kept anywhere or a way to get more verbose output to see what might be failing?

**Comment by rwoodpecker** [comment]
Same issue for me.

**Comment by wsc96** [comment]
Any updates on this issue?

**Comment by deepjyoti30** [comment]
@wsc96 @rwoodpecker Sorry guys. I was not aware of the issue. It was due to some issues in youtube-dl. Its fixed now. Please update to v0.2-r5.
