### ISSUE TITLE
Refactor providers

### ISSUE THREAD

**Issue by danimateo** [deepjyoti30/ytmdl#103]
Make an abstract base class Song with concrete classes for each provider and implement `get_more_data()` on each one (the ones that already have enough data should just pass) and make it a member function. This way, There is no need to check if the provider is in a dict, just need to call `song.get_more_data()` and it's handled for every case.

**Comment by danimateo** [comment]
See #105 or #104

**Comment by deepjyoti30** [comment]
@danimateo Sounds like a good idea but I might not go along with this approach at the moment, let's give it some thought and see if it would be the best way  to go.

If we are doing some refactoring then I want to make sure that later there won't be any need to refactor again so I will take a look at the PR but I might end up rejecting it or keeping it stale ATM.

**Comment by danimateo** [comment]
Yeah sure, I got annoyed because I added 2-3 more files and they seemed like a lot, a refactor is probably needed but the layout of the folders could use some improvement, so by all means analyze for yourself and see.
