### ISSUE TITLE
Missing AUR Dependencies

### ISSUE THREAD

**Issue by Nesaijn** [deepjyoti30/ytmdl#107]
While installing ytmdl from the AUR, I noticed that there are some dependencies still missing:
```
extra/python-pip
community/python-pycountry
```

This is the error while installing when pip is missing:
```
==> Starting build()...
Installing inaSpeechSegmenter using pip since it's not available in AUR.
/tmp/trizen-zodd/ytmdl/PKGBUILD: line 43: pip: command not found
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build ytmdl - makepkg exited with code: 4
```

This is the error I got when not having pycountry installed:
```bash
$ ytmdl
Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 19, in <module>
    from ytmdl import (
  File "/usr/lib/python3.8/site-packages/ytmdl/metadata.py", line 3, in <module>
    import itunespy
  File "/usr/lib/python3.8/site-packages/itunespy/__init__.py", line 23, in <module>
    import pycountry
ModuleNotFoundError: No module named 'pycountry'
```

**Comment by deepjyoti30** [comment]
@Nesaijn Yeah, I am aware of the issue. I've been meaning to fix it however I think I will just add ```inaSpeechSegmenter``` to AUR as a maintainer and then change the ```PKGBUILD``` of ```ytmdl``` accordingly.

For the time being you can install the dependency ```inaSpeechSegmenter``` using pip and also that ```pycountry``` dependency seems weird, since nobody has ever faced that issue.

**Comment by Nesaijn** [comment]
Yeah, I just install pip manually and the installation went without problems. 
Regarding `pycountry`, the latest comment in the [AUR](https://aur.archlinux.org/packages/ytmdl/) also mentions `pycountry`. Other than that, I can only show the error I got, which was solved when installing `pycountry` manually.

**Comment by deepjyoti30** [comment]
@Nesaijn This issue should be fixed now. Made tensorflow optional and pypi has now extra features that can be installed optionally in order for trim to work.

You can install from AUR and report back here if you find any more bugs.

**Comment by Nesaijn** [comment]
I have deinstalled ytmdl, pip and pycountry.

**Comment by deepjyoti30** [comment]
@Nesaijn Thanks for the input.

I completely forgot about unidecode. I have added it now.

Regarding the providers, the code surely supports it for now but I will update the README etc once I do a proper release in a few weeks.
