### ISSUE TITLE
Example Config setting for METADATA_PROVIDERS

### ISSUE THREAD

**Issue by Nesaijn** [deepjyoti30/ytmdl#108]
In the README it is said that there is a [supported option](https://github.com/deepjyoti30/ytmdl#supported-options-to-change-are) to change the metadata providers, but couldn't find an example to see what is possible.
I would be nice to see the options that can be passed to that option.

Also I found a typo in the config:
https://github.com/deepjyoti30/ytmdl/blob/master/ytmdl/setupConfig.py#L17

There it should be "the" instead of "thw".

**Comment by danimateo** [comment]
In the config, right above the METADATA_PROVIDERS there are the available providers.

**Comment by deepjyoti30** [comment]
@Nesaijn The support for metadata providers was added after the last release. That is why it is in the README but it is not supported yet if you're using a released version.

Once the feature is added in a release, you'll be able to use it. Also the README would be updated accordingly just after the release.

If you feel like trying out the feature, you can install the latest commits from the master repo and try it out as @danimateo said.

However, it might have bugs so feel free to raise an issue.

**Comment by Nesaijn** [comment]
Ah, I see. Thank you both!
