### ISSUE TITLE
[Feature] Assign info manually when he doesn't found data for a song from a playlist

### ISSUE THREAD

**Issue by DarkSiider77** [deepjyoti30/ytmdl#109]
Hi,
When I download song from my playlist i have some song without data, the feature allow at the end of download to assign manually name and artist song or change search name for provider.

**Comment by deepjyoti30** [comment]
Hey @DarkSiider77 Did you try passing the `--manual-meta` flag??

Also changing the metadata provider will be supported from the next release. If you check the commits, you'll see it's already in the works. If you want you can even try it out right now.
