### ISSUE TITLE
Add filter/tag for Youtube generated videos to ensure audio quality

### ISSUE THREAD

**Issue by dnswd** [deepjyoti30/ytmdl#113]
I think it would be great if I can choose to download music from youtube generated music because I believe it has more audio quality and no background noise, unlike several MV.

Generated videos usually only have song's album in the video, and the description usually contains `Auto-generated by YouTube.` or `Provided to YouTube by <music company>`

Not every artist has youtube generated music due to contract disagreement, or the artist might not be considered as "well-known" by Youtube. But it would be a very nice touch if I can differentiate youtube generated videos with others.

**Comment by deepjyoti30** [comment]
@dnswd This sounds like a good feature, I will take a look to see if this would be possible to add.

**Comment by deepjyoti30** [comment]
@dnswd I'm currently working on adding this feature. Can you please provide me some sample YouTube links that have the `Auto Generated by YouTube` in the description as well as the other one.

**Comment by deepjyoti30** [comment]
@dnswd Just added support for that. You can check f43a3705dc87fbc84afc98e869d222b3b67aede7

If the song is determined as a music provided by YouTube, it will be indicated with a `[M]` before the name of the song.

I tested with [this](https://www.youtube.com/watch?v=jJSn-HWPDdg) song. However, if you can gimme some more videos, I would be glad to test out with those.
Also in case you face any bugs, you can reply back here.

**Comment by deepjyoti30** [comment]
Added in the latest release
