### ISSUE TITLE
[REQUEST] Opus support?

### ISSUE THREAD

**Issue by Shnxxx** [deepjyoti30/ytmdl#114]
I really love your project. I've tried it for a couple of songs and I didn't get any problem for now. But it would be also nice if you add support for OPUS? It is currently a great file audio format. An audio format that could go on par with FLAC and APE, and superior to AAC which is better than MP3.

Especially on YouTube, because the MKV container and lossless codecs like PCM and FLAC are in fact supported.
But even then, if the user does in fact upload their audio in AAC, YouTube will in fact still transcode it for their AAC encodes. YouTube also recommends uploading at 48KHz, but only their Opus encodes are in 48KHz - YouTube uses 44.1KHz for both AAC and Vorbis, so both of those encodes are likely to have been downsampled as well.

In the end, Opus should still be of higher quality.

As ffcvt suggested, "_the Opus audio codec is becoming the best thing ever for compressing audio -- A 64K Opu audio stream is comparable to mp3 files of 128K to 256K bandwidth_".

Here are some sound samples comparing MP3 and OPUS that shows how superior the OPUS is: [SAMPLES](https://docs.google.com/document/d/1DnD1eoDleJ3rmclV4Is9-1M-j2SE4Gl6833wkij-cvc/edit#heading=h.rloe925wh3ol)

**Comment by Shnxxx** [comment]
The provided link also tells more about the OPUS and not just samples.

**Comment by deepjyoti30** [comment]
@Shnxxx Thanks for the suggestion, I think I had considered adding support for Opus way back when I was adding m4a as a format. The issue, as I remeber, was probably that Opus does not support meta tags? I'm not completely sure about that but this is probably the reason it was not added along with m4a as a format.

However, I'll take another look at it and if possible I'll surely add support. I just think that if the song format won't support metadata then it wouldn't make sense adding support through `ytmdl`

**Comment by deepjyoti30** [comment]
Hey @Shnxxx Added support for `opus` in f3b937a09e5fccf6218649364484360cc7f52120

Considering trying it out and if you have any issues you can report back here.

**Comment by Shnxxx** [comment]
I will try this right away! Thank you for your work. Give me some time to test it out.

**Comment by Shnxxx** [comment]
After installing using `pip install ytmdl` and when I try to do `ytmdl "test" --nolocal` it is saying `'ytmdl` is not recognized as an internal or external command, operable program or batch file."

I did try downloading the ytmdl-master and open setup.py normally but it shows `WARNING: The wheel package is not available.`

I also did try opening CMD in the ytmdl-master directory and used `python ytmdl "test" --nolocal` but it is returning `can't find __main__ module in 'ytmdl'`

I also tried `python setup.py` but it is returning `WARNING: The wheel package is not available.`

Am I missing something?

**Comment by deepjyoti30** [comment]
@Shnxxx I'm assuming you're trying to run it on Windows?

`ytmdl` currently doesn't support windows. However, you can try using it through WSL, users have reported it working through that.

**Comment by Shnxxx** [comment]
I forgot to mention. Yeah, I'll do that right away! Thank you again!

**Comment by deepjyoti30** [comment]
Added in the latest release
