### ISSUE TITLE
Failed while moving with error: 'track_name'

### ISSUE THREAD

**Issue by Pirols** [deepjyoti30/ytmdl#115]
## Issue
Hi, when I run

`$ ytmdl a reason to fight # any song actually`

After asking me which song to download from youtube, downloading it and gathering the correct metadata ytmdl exits with the following error and failing to create any directory(let alone moving the file from the cache folder):
> Failed while moving with error: 'track_name'

The found metadata is correct, as follows
>  || YEAR: 2018-10-19T12:00:00Z
  || TITLE: A Reason to Fight
  || ARTIST: Disturbed
  || ALBUM: Evolution (Deluxe)
  || GENRE: Rock
  || TRACK NO: 3
  || ALBUM COVER ADDED

Here follows the content of my ~/.cache/ytmdl/logs/log.cat
> [ytmdl]-[2020-8-27 21:48:12]: Logger running in DEBUG mode
[ytmdl]-[2020-8-27 21:48:12]: Passed args: Namespace(SONG_NAME=['a', 'reason', 'to', 'fight'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='m4a', ignore_errors=False, level='INFO', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url=None)
[ytmdl]-[2020-8-27 21:48:12]: ['a', 'reason', 'to', 'fight']
[ytmdl]-[2020-8-27 21:48:12]: a reason to fight
[cache]-[2020-8-27 21:48:12]: Searching to see if already present in /home/pirols/music
[ytmdl]-[2020-8-27 21:48:12]: proxy passed: None
[ytmdl]-[2020-8-27 21:48:12]: Passed format: m4a
[ytmdl]-[2020-8-27 21:48:12]: Searching Youtube for ESC[93ma reason to fightESC[0m
[ytmdl]-[2020-8-27 21:48:41]: {'title': 'Disturbed - A Reason To Fight [Official Music Video]', 'href': '/watch?v=t4382UVl0oc', 'author_name': 'Disturbed', 'duration': '4:48'}
[ytmdl]-[2020-8-27 21:48:41]: Downloading ESC[95mDisturbed - A Reason To Fight [Official Music Video]ESC[0m in ESC[93m320kbpsESC[0m
[yt]-[2020-8-27 21:48:41]: Saving the files to: /home/pirols/.cache/ytmdl
[yt]-[2020-8-27 21:48:41]: /home/pirols/.cache/ytmdl/Disturbed#-#A#Reason#To#Fight#[Official#Music#Video].m4a
[ytmdl]-[2020-8-27 21:48:46]: Downloaded!
[ytmdl]-[2020-8-27 21:48:46]: Skip Meta: False
[ytmdl]-[2020-8-27 21:48:46]: Getting song data for a reason to fight...
[song]-[2020-8-27 21:48:48]: Preparing the album cover
[Dir]-[2020-8-27 21:48:48]: Failed while moving with error: 'track_name'

## Context:
My operating system is Artix linux (the runit version), it is completely up to date and I have installed the git version of ytmdl from the AUR.
My ~/.config/ytmdl/config file sets the following variables:
> SONG_DIR = "/home/pirols/music$Genre->Artist->Album->[Title]
QUALITY = "320"
METADATA_PROVIDERS = "itunes, gaana"
DEFAULT_FORMAT = "m4a"

## Isolating the issue

* The problem doesn't show up if you run the same command with root privileges, unfortunately this comes with some shortcomings as the configurations in the config file won't be used.
* I have umask set to 077, anyway also running it with umask set to 022 and changing the permission of the ~/music folder won't fix the issue.
* Pre-creating the directories fixes the issue. In particular I have created ~/music/G/B/A and fed these values manually as metadata with the -m option and the song was moved without any error(besides the lack of the album cover which I didn't bother looking up) being returned.

**Comment by deepjyoti30** [comment]
@Pirols I'll try to reproduce the issue, however as seen in your config, is the SONG_DIR quote not closed??

> SONG_DIR = "/home/pirols/music$Genre->Artist->Album->[Title]

and not

> SONG_DIR = "/home/pirols/music$Genre->Artist->Album->[Title]"

If it is closed, I think the issue might be probably while creating the directories dynamically which I am going to take a look at ASAP.

**Comment by deepjyoti30** [comment]
@Pirols Should be fixed in de1fa38 Consider trying out that commit and report back here if you face any more issues.

**Comment by Pirols** [comment]
> @Pirols I'll try to reproduce the issue, however as seen in your config, is the SONG_DIR quote not closed??

It was a typo, mb!

> @Pirols Should be fixed in [de1fa38](https://github.com/deepjyoti30/ytmdl/commit/de1fa38a7e319ba46ca2b0a3225dced02fd37eeb) Consider trying out that commit and report back here if you face any more issues.

Just tested and it now works flawlessly!
