### ISSUE TITLE
Last.fm Integration

### ISSUE THREAD

**Issue by nesper8** [deepjyoti30/ytmdl#118]
Can you consider integrating last.fm to grab metadata of songs as its have a very detailed sections

**Comment by deepjyoti30** [comment]
@nesper8 I'll take a look at their API. I will add support if it is plausible.

**Comment by deepjyoti30** [comment]
@nesper8 I'll be pushing the commits shortly. Last FM support will be added. Cheers!

**Comment by deepjyoti30** [comment]
@nesper8 The feature will be added in the next release. In the meanwhile you can try it out by cloning and installing the latest commits.

Feel free to report back here if something doesn't work

**Comment by nesper8** [comment]
Thank you ill close this issue now
