### ISSUE TITLE
Can't use the command 

### ISSUE THREAD

**Issue by georgeat8** [deepjyoti30/ytmdl#121]
# Bug report
Error on running command: 

`Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 22, in <module>
    from ytmdl import (
  File "/usr/lib/python3.8/site-packages/ytmdl/song.py", line 26, in <module>
    from ytmdl import prepend, defaults
ImportError: cannot import name 'prepend' from 'ytmdl' (/usr/lib/python3.8/site-packages/ytmdl/__init__.py)`

## Checklist

[x] I have searched for similar bugs in the issues.
[x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: 2020.11.20
- Youtube-dl version: 2020.11.17

## How Ytmdl was installed?

Through AUR, using the [ytmdl](https://aur.archlinux.org/packages/ytmdl/) package.

## Description

I'm having the issue mentioned above, which stops me from even using `ytmdl --version`.
OS is Manjaro KDE.

**Comment by phykos** [comment]
I encountered this too, weird

**Comment by deepjyoti30** [comment]
@phykos @georgeat8 Sorry about all the issues. Should be fixed now. Updated the version in both pypi as well as AUR.

**Comment by phykos** [comment]
> @phykos @georgeat8 Sorry about all the issues. Should be fixed now. Updated the version in both pypi as well as AUR.

I'll try, thx

**Comment by phykos** [comment]
Works!
