### ISSUE TITLE
Fetch Meta data from musicbrainz

### ISSUE THREAD

**Issue by ThangaAyyanar** [deepjyoti30/ytmdl#124]
# Metadata data fetch

## Checklist
[ ] Fetch Metadata from Musicbrainz along with other sources.

## Description
Music brainz maintain metadata of music and it is public, Integrating it would be pretty cool.

Site: https://musicbrainz.org/
API: https://musicbrainz.org/doc/MusicBrainz_API

**Comment by deepjyoti30** [comment]
@ThangaAyyanar Thanks for the suggestion. Seems like a nice addition. I will consider adding this.

**Comment by deepjyoti30** [comment]
@ThangaAyyanar Musicbrainz is added. You can check 9e04fd856f5ffe and commits before that.

Feel free to clone the latest commits from the unstable branch and try it out youreslf. You can report back here if you find any issues.

**Comment by deepjyoti30** [comment]
Added in the next release
