### ISSUE TITLE
While downloading youtube playlists, add ability to skip the prompt "Most extracted titles are not accurate and they affect the meta search""

### ISSUE THREAD

**Issue by dsivasuthan** [deepjyoti30/ytmdl#129]
# Feature Request

## Checklist

[x] I've searched the bugtracker for similar feature requests including closed ones.
[x] I will add the enhancement label to the issue.

## Description

Add a flag/switch to disable any prompt while downloading playlists. Currently, it asks if you want to change the metadata. Most of the songs I download don't have metadata, so I want to skip the search. Thanks.

**Comment by deepjyoti30** [comment]
@dsivasuthan So you want to skip the part where metadata is searched? Have you tried the `--skip-meta` flag?

Also you can use the `--ignore-errors` to continue downloading if meta fails.

**Comment by dsivasuthan** [comment]
Yeah, I tried those switches. The following was my exact command but it still asks if I want to manually change meta.

`ytmdl --disable-metaadd --skip-meta -q --ignore-errors https://www.youtube.com/playlist\?list\=PL_DaWb6RFQc0nKvAnLOFDk_tmOtp1VX9x`

**Comment by deepjyoti30** [comment]
@dsivasuthan So you want to be able to skip the prompt where the user is asked if they'd like to change the title of the song before the meta search is done?

**Comment by dsivasuthan** [comment]
Exactly! I think this option would make this similar to youtube-dl but it would be helpful for certain playlist cuz we don't need to keep hittin "n" and Enter for each song. I hope that makes sense. Thank you.

**Comment by deepjyoti30** [comment]
@dsivasuthan I understand. I did have that in mind however considering that most songs cannot be found with the YouTube title I did not add that flag.

**Comment by deepjyoti30** [comment]
@dsivasuthan Added in 2296697dd9975a12c6f06.

You can check the latest commits and report back here if it doesn't work for you.

**Comment by dsivasuthan** [comment]
That totally worked! :) Thank you for the speedy response. Now, I just need to find a way to slow this down so youtube doesn't think I am abusing.

**Comment by deepjyoti30** [comment]
Added in `2021.1.14`.
