### ISSUE TITLE
Error while converting file to mp3

### ISSUE THREAD

**Issue by melonhusk** [deepjyoti30/ytmdl#13]
Tried downloading a song,
Download was complete, then it stopped and displayed the following error

Problems : 
1. No AlbumArt
2. #The#Name#Is#Like#This
3. The song doesn't play in my phone, but does on my laptop

Bruno#Mars#-#Grenade#[Official#Video].mp3                                                                                                3.64 MB's |36 kbps| ETA: 0 s |--------------------| 100.00%
 ==> Downloaded!
 ==> Converting to mp3...
 ==> Something went wrong while converting!
 ==> Getting song data...
 ==> Setting data...
 ==> Choose One
 [1] Grenade by Bruno Mars
 [2] Grenade by Bruno Mars
 [3] Grenade by Bruno Mars
 [4] Grenade by .GRENADE
 [5] Grenade by Power Music Workout
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Something went wrong while writing data!

**Comment by deepjyoti30** [comment]
Fixed in [#810593](https://github.com/deepjyoti30/ytmdl/commit/8105932fc55698222eab1e6457e00ef01b43093d)
