### ISSUE TITLE
can only download from youtube

### ISSUE THREAD

**Issue by mohibo** [deepjyoti30/ytmdl#133]
# Bug report

## Checklist

[x] I have searched for similar bugs in the issues.
[ ] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `Web Version`
- Youtube-dl version: `I Don't Have It`

## How Ytmdl was installed?
I'm Using The Web Version
Write here how you installed ytmdl. If it was through pip or some other way.

## Console Log

```console
PUT LOG HERE. Get the log by running ytmdl in `DEBUG` by `--level DEBUG` flag.
```

## Description
i can only download songs from youtube,no deezer,no saavn
DESCRIBE THE ISSUE
i can only download songs from youtube,no deezer,no saavn

**Comment by deepjyoti30** [comment]
@mohibo The audio is always extracted from YouTube and the metadata is fetched from sources like deezer and lastfm.

It's clearly stated in the [README](https://github.com/deepjyoti30/ytmdl/tree/unstable#why-this)

**Comment by deepjyoti30** [comment]
Not a bug
