### ISSUE TITLE
Some songs can't find metadata from itunes.

### ISSUE THREAD

**Issue by Tennyleaz** [deepjyoti30/ytmdl#137]
# Bug report

## Version Info

- Ytmdl version: `2020.11.20-1`
- Youtube-dl version: `2020.11.01.1`

## How Ytmdl was installed?
From pip3

## Console Log

```console
$ ytmdl アカシア --level DEBUG
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=['アカシア'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url=None)
 ==>  ['アカシア']
 ==>  アカシア
 ==>  Searching to see if already present in /home/tenny/Music
 ==>  proxy passed: None
 ==>  Passed format: mp3
 ==>  Searching Youtube for アカシア
 ==> Choose One (One with [M] is verified music)
 [1] 【Official】Pokémon Special Music Video 「GOTCHA！」 | BUMP OF CHICKEN - Acacia by ポケモン公式YouTubeチャンネル with dur 3:15
 [2] [M] Acacia by BUMP OF CHICKEN with dur 4:23
 [3] ｢Acacia｣ フル【60分耐久】BUMP OF CHICKEN by すいそまる with dur 1:03:48
 [4] 【公式】『ポケモン ソード・シールド ＋ エキスパンションパス』スペシャル PV | BUMP OF CHICKEN - アカシア by ポケモン公式YouTubeチャンネル with dur 3:22
 [5] 【MAD】アニメ ポケットモンスター 『アカシア ーAcaciaー』『GOTCHA！』Pokémon by アレルヤ with dur 4:19
 [0] More results
 ==> Enter Choice [default is 1] 2
 ==>  {'title': 'Acacia', 'href': '/watch?v=4dnT-kKIO6Y', 'author_name': 'BUMP OF CHICKEN', 'duration': '4:23', 'verified_music': True}
 ==>  Downloading Acacia in 320kbps
 ==>  Saving the files to: /home/tenny/.cache/ytmdl
 ==>  /home/tenny/.cache/ytmdl/Acacia.mp3
4 MB   | 8 Mb/s || ETA: 5 s                                                                                                           |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==>  Downloaded!
 ==>  Converting to mp3...
 ==>  Skip Meta: False
 ==>  Getting song data for アカシア...
 ==> Setting data...
 ==> Choose One
 [1] Magic by Highlnd & Akacia
 [2] Home by Miqui Brightside & Akacia
 [3] Mary by Akacia
 [4] Run by Alvaro Delgado, Alltair & Akacia
 [5] In the Air by Akacia
 [0] More results
 ==> Enter Choice [default is 1] 0
 [6] Unfading Divine by Akacia
 [7] Mystery by Akacia
 [8] Fear by Darwin, Mainecoon & Akacia
 [9] Acacia by EXILE THE SECOND
 [10] Smoke & Mirrors by ShyGhy & Akacia
 [0] More results
 ==> Enter Choice [default is 1]

```

## Description

For example [this song](https://music.apple.com/jp/album/1532188552) is on itunes (and [youtube music](https://music.youtube.com/playlist?list=OLAK5uy_kQheEFKaoGGt2cqrFiYls0l9VudqWUymg), [amazon music](https://music.amazon.co.jp/albums/B08JCFNMSD), spotify...), but ytmdl cannot find any related metadata.

**Comment by deepjyoti30** [comment]
@Tennyleaz Can you give me a bit more details regarding the song? Google translates indicates that `アカシア` means `acacia` so is the name of the song acacia?

Also, from the Itunes link it seems like the name of the song is Bump of chicken?! Do you mind telling me the name of the singer and the album.

I think the issue is probably that the song is available in the results but it is way down due to the sorting algo applied by `ytmdl`. If that's the case, I would like to fix the issue.

**Comment by deepjyoti30** [comment]
@Tennyleaz Found the issue. It is happening because `ytmdl` is trying to show you the songs that are most related to the current song, first. However the algo used to determine that is pretty `naive`. Since your songs name is entered in japanese it is not showing the closest result first because it doesn't consider converting the song name.

I am thinking of adding a flag to disable the sorting feature so users can see a raw result of the searched objects.

**Comment by Tennyleaz** [comment]
@deepjyoti30
Thanks for your reply. `アカシア` a.k.a. `Acacia` is the name of the song, and artist is `Bump of chicken`. I also tried command like `ytmdl アカシア --artist Bump of chicken`, and it gives me similar result.

Glad that you could fix this issue in the future.

**Comment by deepjyoti30** [comment]
@Tennyleaz Added a flag `--disable-sort` to disable the sorting before showing the metadata to the user.

Tried with your song as well, it's working fine. Feel free to try the commit and report back here if you find any bug.

The commit is 868a1339095e7bd86ff0585ef442e460724b316a

**Comment by Tennyleaz** [comment]
@deepjyoti30 
Using commit `868a133` with argument `ytmdl アカシア --artist 'Bump of chicken' --disable-sort` finally shows correct metadata. 
Thanks!

**Comment by deepjyoti30** [comment]
Added in `2021.1.14`.
