### ISSUE TITLE
Enhance --title-as-name flag to disable asking to change song title for timestamps/chapters

### ISSUE THREAD

**Issue by BobDaGecko** [deepjyoti30/ytmdl#141]
# Feature Request

## Checklist

 - [x] I've searched the bugtracker for similar feature requests including closed ones.
 - [x] I will add the enhancement label to the issue.

## Description
This feature is already made for playlists with the --title-as-name flag but also add support for chapters/timestamps to disable having to enter `n` every time a chapter/timestamp is extracted.

Also add a wait time between extraction of playlists and chapters when using this flag to avoid being flagged by YouTube for abuse as referenced in #129

**Comment by deepjyoti30** [comment]
@BobDaGecko This is already a feature. You can use the `--keep-chapter-name` flag to do that.

**Comment by BobDaGecko** [comment]
Wow, works great, thanks! I didn't know the flag existed, you may want to add it to the README and wiki.
