### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by chri87d9** [deepjyoti30/ytmdl#15]
I'm having trouble when changing the config file. I have changed the SONG_DIR, but it is still using the default. I removed the # in the beginning of the line, so it says:

SONG_DIR = "home/chris"

**Comment by deepjyoti30** [comment]
I think you should change it to ```SONG_DIR="/home/chris"```, the ```/``` before is important.

It takes the dir from the config but when it also checks to see if it is present, else the dedault dir is used.

**Comment by chri87d9** [comment]
I have tried, but it doesn't seem to be reading. I deleted the default created dir, I just get the output:


Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 217, in <module>
    extract_data()
  File "/usr/bin/ytmdl", line 212, in extract_data
    main(args)
  File "/usr/bin/ytmdl", line 91, in main
    if not cache.main(song_name):
  File "/usr/lib/python3.7/site-packages/ytmdl/cache.py", line 84, in main
    match = cache.search(SONG_NAME)
  File "/usr/lib/python3.7/site-packages/ytmdl/cache.py", line 55, in search
    return self._search_tokens(song_name)
  File "/usr/lib/python3.7/site-packages/ytmdl/cache.py", line 61, in _search_tokens
    cached_songs = self.list_mp3()
  File "/usr/lib/python3.7/site-packages/ytmdl/cache.py", line 34, in list_mp3
    os.chdir(self.directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/Music

But this error is kust related to me deleting the default dir, right?

**Comment by deepjyoti30** [comment]
@chri87d9 I'm sorry about the error. It is actually caused because before downloading the song, ```ytmdl``` tries to check if the song is present locally and it checks that in the current ```~/Music``` dir.

I think you won't face the same issue with the latest release. 

You can try cloning the repo and get it fixed, else you can try passing the flag ```--nolocal``` to ytmdl.

This sure would be fixed in the next update.

**Comment by chri87d9** [comment]
the '--nolocal' stopped the error, but it still ingnores my config, and just downloads to the default directory. Maybe its an issue on my end?

**Comment by deepjyoti30** [comment]
Hey @chri87d9 the issue will be fixed in the next release.
