### ISSUE TITLE
Always getting an error

### ISSUE THREAD

**Issue by abrasivetroop** [deepjyoti30/ytmdl#150]
## How Ytmdl was installed?

I used pip and I have python3.6.9 and ffmpeg installed. I am on elementaryOS.

## Console Log

```console

Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 19, in <module>
    from ytmdl import (
  File "/usr/local/lib/python2.7/dist-packages/ytmdl/song.py", line 51
    print(Fore.LIGHTMAGENTA_EX, end='')
                                   ^
SyntaxError: invalid syntax

```

## Description

Always getting this error it doesn't work at all.

**Comment by deepjyoti30** [comment]
@abrasivetroop  Is it possible you have two versions of python installed? Seems like the ytmdl script is being run by `python2` and that's why this error is showing up.
