### ISSUE TITLE
Interactive song data re-set

### ISSUE THREAD

**Issue by elig0n** [deepjyoti30/ytmdl#152]
# Feature Request

## Description

Please allow an option to change the search query to the song data provider interactively when asked to choose one of the results for cases when the search query for Youtube doesn't fit the song data provider.

This will prevent cancel of sessions where the song was already downloaded from Youtube but a re-run is required to fix song data search terms.

P.S. I'm aware of --song.

**Comment by deepjyoti30** [comment]
@elig0n Seems valid. I will consider this for the next release.

**Comment by deepjyoti30** [comment]
@elig0n Should be added in dc132268ea7a02d1af9f0fccc9db9d4171176d49 Please consider taking a look at the commit and report back if it doesn't work.

**Comment by deepjyoti30** [comment]
Added in the latest release
