### ISSUE TITLE
[freyr-js]: Alternative supporting multiple services, many features and customization options

### ISSUE THREAD

**Issue by miraclx** [deepjyoti30/ytmdl#154]
Nice work on this; I've been working on something similar for the past year now

**freyr-js** https://github.com/miraclx/freyr-js
- supports multiple streaming services (Spotify, Apple Music, Deezer, and more to come)
- automatically embeds album art and song metadata
- exports M4A audio supported in iTunes
- has a myriad of options for customizing the experience (Alternate sources, preferred bitrate, etc...)
- minimal dependencies
- lightweight Docker [images](https://hub.docker.com/r/freyrcli/freyrjs/tags)
- and many more features

### Service Support

| Service | Track | Album | Artist | Playlist | [URI Short Tags](https://github.com/miraclx/freyr-js/blob/master/README.md#uris) |
| :-----: | :---: | :---: | :----: | :------: | :------------: |
| [Spotify](https://github.com/miraclx/freyr-js/blob/master/src/services/spotify.js) |   ✔   |   ✔   |    ✔   |     ✔    | `spotify:` |
| [Apple Music](https://github.com/miraclx/freyr-js/blob/master/src/services/apple_music.js) |   ✔   |   ✔   |    ✔   |     ✔    | `apple_music:` |
| [Deezer](https://github.com/miraclx/freyr-js/blob/master/src/services/deezer.js) |   ✔   |   ✔   |    ✔   |     ✔    | `deezer:` |
| Youtube Music (See [#6](https://github.com/miraclx/freyr-js/issues/6)) |   ✗   |   ✗   |    ✗   |     ✗    | ✗ |

### Metadata Availability

|      Meta      | Spotify | Apple Music | Deezer |
| :------------: | :-----: | :---------: | :----: |
| `Title`        |   ✔   |     ✔     |   ✔  |
| `Artist`       |   ✔   |     ✔     |   ✔  |
| `Composer`     |   ✗   |     ✔     |   ✔  |
| `Album`        |   ✔   |     ✔     |   ✔  |
| `Genre`        |   ✗   |     ✔     |   ✔  |
| `Track Number` |   ✔   |     ✔     |   ✔  |
| `Disk Number`  |   ✔   |     ✔     |   ✔  |
| `Release Date` |   ✔   |     ✔     |   ✔  |
| `Rating`       |   ✔   |     ✔     |   ✔  |
| `Album Artist` |   ✔   |     ✔     |   ✔  |
| `ISRC`         |   ✔   |     ✔     |   ✔  |
| `Label`        |   ✔   |     ✔     |   ✔  |
| `Copyright`    |   ✔   |     ✔     |   ✗  |
| `Cover Art`    |   ✔   |     ✔     |   ✔  |

Do check it out... https://github.com/miraclx/freyr-js

**Comment by deepjyoti30** [comment]
Not an enhancement
