### ISSUE TITLE
"~" character not supported in config

### ISSUE THREAD

**Issue by hussein-esmail7** [deepjyoti30/ytmdl#159]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2021.01.14-1`
- Youtube-dl version: `2021.01.16`

## How Ytmdl was installed?

I installed Ytmdl via pip on my macOS machine (macOS Catalina).

## Description

In the config file, I tried to use the "~" character to refer to the home directory but it was not accepted. I know this because "/Users/hussein/..." worked. I was wondering if this can be fixed so that it's easier for people to read and write in this file. Thank you.

**Comment by deepjyoti30** [comment]
@hussein-esmail7 I am aware that the `~` is not parsed to the home directory. I think this can be fixed.

**Comment by deepjyoti30** [comment]
@hussein-esmail7 Should be fixed in 54a9139
