### ISSUE TITLE
Cannot download any songs

### ISSUE THREAD

**Issue by sacred58** [deepjyoti30/ytmdl#160]
# Bug report

## Checklist

- [*] I have searched for similar bugs in the issues.
- [*] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2021.01.14-1`
- Youtube-dl version: `2021.02.04.1`

## How Ytmdl was installed?

pip3

## Console Log

 ==> Passed args: Namespace(SONG_NAME=[], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, disable_sort=False, format='mp3', get_opts=False, ignore_errors=False, keep_chapter_name=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, title_as_name=False, trim=False, url=None) 

## Description

Whenever I try and download a song, it successfully saves the song to the ~/.cache/ytmdl directory before sending the error:

y
![ytmdl_error](https://user-images.githubusercontent.com/78624958/107099676-9031b500-67cf-11eb-8582-0df59a584350.png)
Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 456, in <module>
    extract_data()
  File "/usr/local/bin/ytmdl", line 451, in extract_data
    main(args)
  File "/usr/local/bin/ytmdl", line 244, in main
    chapters = yt.get_chapters(link)
  File "/usr/local/lib/python3.8/dist-packages/ytmdl/yt.py", line 349, in get_chapters
    return info["chapters"]
KeyError: 'chapters'
 
I have tried ytmdl on another machine and was presented with the same issue

Edit: I found a temporary fix, commenting out line 349 in /usr/local/lib/python3.8/dist-packages/ytmdl/yt.py seems to fix the issue, I imagine doing this disables any functionality relating to chapters. I'm not experienced enough as a programmer to explain why this solution works, it was kinda just something that I tried. Hope this can help anyone else having this issue

**Comment by deepjyoti30** [comment]
@sacred58 Is this error showing up with every song you're trying to download?

**Comment by deepjyoti30** [comment]
@sacred58 Should be fixed in f763167

**Comment by sacred58** [comment]
Thanks
