### ISSUE TITLE
[Feature] Using local song-file or playlist-direcotry instead of downloading it

### ISSUE THREAD

**Issue by ruru4143** [deepjyoti30/ytmdl#161]
# Feature Request

I currently have a big music libary downloaded and i want to enchance it with metadata. Because of that i want to parse a song file or a playlist directory from where ytmdl can work on.

## Checklist

- [X] I've searched the bugtracker for similar feature requests including closed ones.
- [X] I will add the enhancement label to the issue.

## Description

```
  SONG_NAME             Name of the song to download. Can be an URL to a playlist **or a local file/directory** as well. It will be automatically recognized.
```

**Comment by deepjyoti30** [comment]
@ruru4143 So you want to be able to add metadata to existing song files that you have. Isn't this a duplicate of #153 ?!

**Comment by ruru4143** [comment]
Oh. It is, i didn't see it. thanks
