### ISSUE TITLE
Failed to change the SONG-DIR

### ISSUE THREAD

**Issue by akhilsaini678** [deepjyoti30/ytmdl#163]
I have changed SONG-DIR in config file but it is still saving songs in default folder.

**Comment by deepjyoti30** [comment]
@akhilsaini678 Can you share a copy of the config? Also try running `ytmdl` with the log level set to `DEBUG` in the following way:

```console
ytmdl ``<SONG-NAME> --level DEBUG
```

It might be that the way you've set the `SONG-DIR` is not valid and that is why `ytmdl` is falling back to the default directory instead of using the one provided by you.

**Comment by akhilsaini678** [comment]
#*****************************************#
#*-------------config for ytmdl-----------#
#
#-----------------------------------------#
#------PLEASE DON'T LEAVE ANY BLANK LINES---#
#-----------------------------------------#
#
# To change defaults just remove the hash(#)
# from the beginning of the line.
#
#*****************************************
# The SONG_DIR is the directory where all the songs will be saved.
# In order to change it, simply remove the hash from beginning
# And change the path to your desired one.
# In case the path has spaces in in, include it in a " "
#ccccccc Following is a simple folder path example
#
SONG_DIR = "/data/data/com.termux/files/home/storage/shared/Download"
#
#************--------ADVANCED-------*********
# If you want to save the song in custom folders than those can be
# added to the name like the following example.
# The possible values are following
#
# Artist --> Song Artist
# Album  --> Song Album Name
# Title  --> Song Name
# Genre  --> Song Genre
# TrackNumber --> Song Number in the album
# ReleaseDate --> Song Release date
#
# Following is an example of the format
#SONG_DIR = "/home/user/Music$Artist->Album->Title"
#
#*****************************************#
# The QUALITY is the quality of the song in kbps
# By default it is set to 320kbps
# In case you want to change it to something else,
# Uncomment the following line and change it
#
# Supported values are 320 and 192
#
#QUALITY = "320"
#
#*****************************************#
# The METADATA_PROVIDERS value is a comma separated
# values that specifies wich API providers to use for getting
# the song metadata. Available values right now are:
# itunes, gaana, deezer, lastfm, musicbrainz, saavn.
# Please check the github page of ytmdl for more information.
#
#METADATA_PROVIDERS = "itunes, gaana"
#
#*****************************************#
# The DEFAULT_FORMAT denotes what to use as default for downloading.
# Available values are:
# mp3, m4a, opus
#
#DEFAULT_FORMAT = "mp3"
#

**Comment by deepjyoti30** [comment]
@akhilsaini678 Seems like you're trying to run this on an android device. The path looks okay but I cannot vouch for an Android device. If you can, please share the log by running ytmdl using the `ytmdl <song> --level DEBUG`.

**Comment by akhilsaini678** [comment]
Isn't there any other way to change the directory

**Comment by deepjyoti30** [comment]
@akhilsaini678 We currently do not have any other way to change the song directory. If you want you can share the logs by using the `--level DEBUG` or by sharing the `log file`. Otherwise I cannot help you with the issue.

**Comment by NightMachinary** [comment]
@deepjyoti30 I just installed ytmdl and did no config; It downloads to ~/Music, not the PWD. I trieed `SONG_DIR="$PWD" ytmdl -q --title-as-name --nolocal sth`, with no effect.

**Comment by deepjyoti30** [comment]
@NightMachinary Can you share your config?

I just tried with the latest version and it does download to the current directory.

Also `SONG_DIR="$PWD"` won't have any effect since the `SONG_DIR` expects a path and no special variabled names.

**Comment by deepjyoti30** [comment]
@NightMachinary Just checked the code. The first preferrence is given to the `~/Music` directory. If that is not found then the `XDG_MUSIC_DIR` is tried. Finally if both of them fail, then current directory is used.
