### ISSUE TITLE
--quiet with automatic selection of [M]

### ISSUE THREAD

**Issue by Catwaiix** [deepjyoti30/ytmdl#165]
# Feature Request

## Checklist

- [X] I've searched the bugtracker for similar feature requests including closed ones.
- [X] I will add the enhancement label to the issue.

## Description

Basically I thought it will be useful to add an --quiet-m option that don't ask the user to select songs if more than one search result. The result with [M] tag in each case will be considered.

**Comment by deepjyoti30** [comment]
@Catwaiix I thought that was automatically done since the `[M]` feature was added. I will take a look to see if it's failing or so.

Previously when `--quiet` was passed then the first result was considered but since `[M]` was introduced that was supposed to be considered.

**Comment by Catwaiix** [comment]
Well, as you can see in this screenshot, it considers the first result only. And since some days ago I started getting this 'chapters' error.

https://i.imgur.com/FLhTEbk.png

**Comment by deepjyoti30** [comment]
@Catwaiix I see. I will look into the `--quiet` issue. Also regarding the chapters issue, please consider opening a new issue with proper details on it!

**Comment by Catwaiix** [comment]
Alright so I got the most updated unstable version because I saw commit f763167, and apparently the chapters issue now is gone so I won't open a new issue. Still, in the latest dev version, verified music is not considered when passing --quiet.

<img src="https://i.imgur.com/VLYZsDE.png">
https://imgur.com/VLYZsDE.png

**Comment by deepjyoti30** [comment]
@Catwaiix Should be fixed in bca3534

**Comment by Catwaiix** [comment]
Now it just works™ like a charm! Thank you for everything!

<img src="https://i.imgur.com/028Ttl9.png">
https://imgur.com/028Ttl9.png
