### ISSUE TITLE
Song Not Downloading

### ISSUE THREAD

**Issue by FatSandwich** [deepjyoti30/ytmdl#167]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/bin/ytmdl", line 456, in <module>
    extract_data()
  File "/opt/virtualenvs/python3/bin/ytmdl", line 451, in extract_data
    main(args)
  File "/opt/virtualenvs/python3/bin/ytmdl", line 244, in main
    chapters = yt.get_chapters(link)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ytmdl/yt.py", line 349, in get_chapters
    return info["chapters"]
KeyError: 'chapters'

Version: 2021.1.14.post1

**Comment by deepjyoti30** [comment]
@FatSandwich This is a copy of #160 

Please consider checking that issue for the solution.

**Comment by FatSandwich** [comment]
Thanks, so do I need to wait for that version to come out?

**Comment by deepjyoti30** [comment]
@FatSandwich If you want you can try the fix I provided on that issue and see if it fixes your issue. If you want to wait for the stable version then you'll have to wait, there won't be any fix untill it is released.

**Comment by FatSandwich** [comment]
What do I do with [f763167](https://github.com/deepjyoti30/ytmdl/commit/f7631673ee18a8ce383d5b3872b198570c80f0b4)

**Comment by deepjyoti30** [comment]
@FatSandwich You can pull the latest commits from the unstable branch and install ytmdl to try out the latest changes.

**Comment by FatSandwich** [comment]
I'm not sure how to do that...

**Comment by FatSandwich** [comment]
What do I do when I'm here f7631673ee18a8ce383d5b3872b198570c80f0b4?

**Comment by FatSandwich** [comment]
How do I install ytmdl with this?

**Comment by FatSandwich** [comment]
By the way, I'm using repl.it.

**Comment by FatSandwich** [comment]
I finally got how to pull it but which file do I run?

**Comment by deepjyoti30** [comment]
@FatSandwich Follow the instructions [here](https://github.com/deepjyoti30/ytmdl#manual)

**Comment by FatSandwich** [comment]
How do I clone the unstable branch and not the manual?

**Comment by FatSandwich** [comment]
It says

setup.py:48: UserWarning: ytmdl.bash does not exist, skipping.
  warn("%s does not exist, skipping." % filename)
setup.py:48: UserWarning: ytmdl.zsh does not exist, skipping.
  warn("%s does not exist, skipping." % filename)

**Comment by FatSandwich** [comment]
It's stuck on "Searching Youtube for ..." after

**Comment by FatSandwich** [comment]
Thank you so much!
