### ISSUE TITLE
Is there a way to get specific metadata?

### ISSUE THREAD

**Issue by FatSandwich** [deepjyoti30/ytmdl#168]
I was looking for a song but it couldn't find the metadata. My keyword for the YouTube search was Talk WDW. The song popped up but not the metadata. Is there a way to use different search keywords for the metadata?

**Comment by deepjyoti30** [comment]
@FatSandwich There are two options available. One is the `--song` flag and the other is the `--ask-meta-name` added in #152 .

The `--song` flag should be available in the stable release. However the latter flag is available in the latest unstable branch and will be added to the stable version in the next release.
