### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by lincoln7711** [deepjyoti30/ytmdl#17]
Mac OSX Mojave, iterm2 w/ ZSH

Installed via pip, get the attached syntax error.  My python is up to date (both 2 and 3).  

Also had an issue with it installing on my Ubuntu box (19.10) this morning - wouldn't recognize it as a command after installing via pip.  Haven't really had a chance to look further, but advice welcome.  
<img width="890" alt="Screen Shot 2019-11-15 at 09 28 20" src="https://user-images.githubusercontent.com/50744413/68965459-d1dcd700-07a9-11ea-9579-2bd1198691f1.png">

**Comment by deepjyoti30** [comment]
I think you used pip2 instead of pip3. Try uninstalling and reinstalling using ```pip3```.

That would probably fix the issue.

**Comment by lincoln7711** [comment]
Yep, that was on me.  I didn't specify the version of pip and it used pip2.  Thanks!
