### ISSUE TITLE
"How do you want to open this file?" popup when running ytmdl on windows 10

### ISSUE THREAD

**Issue by Vresod** [deepjyoti30/ytmdl#178]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [X] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2021.03.04`
- Youtube-dl version: `2021.04.17`

## How Ytmdl was installed?

`pip install -U ytmdl`

## Console Log

Not applicable, happens before any ytmdl code runs.

## Description

When the command `ytmdl` is run, it opens a "How do you want to open this file?" prompt, like this
![image](https://user-images.githubusercontent.com/40863375/116167194-b92a5d80-a6cd-11eb-8737-fa0c5fd2bce2.png)
The program itself runs perfectly fine when running it via `python (which ytmdl|% Source)` (finds the location of ytmdl and runs it with python) in PowerShell. I assume the reason this is is because ytmdl in the python Scripts folder has no file extension. This could be rectified by changing it to `ytmdl.py`

**Comment by Vresod** [comment]
the `setup.py` references a file called `ytmdl.bat` which I could not find
![image](https://user-images.githubusercontent.com/40863375/116167452-42419480-a6ce-11eb-9282-68c3555c1e35.png)

**Comment by deepjyoti30** [comment]
@Vresod That's an weird error.

`ytmdl` is supposed to be actually invoked by the `bat` script which in order runs the actual script. I am not sure why you were not able to find the `.bat` file. This file is automatically installed when the OS is recognized as `Windows`.

As you said the popup happens because the file doesn't have any extension, can you perhaps try renaming the file to one with `.py` extension and then running again?

**Comment by Vresod** [comment]
Sorry for taking a while to respond.
When I rename it to ytmdl.py it successfully *starts* the program but errors immediately.
<pre lang=py>
Traceback (most recent call last):
  File "C:\Users\lukeb\AppData\Roaming\Python\Python39\Scripts\ytmdl.py", line 22, in <module>
    from ytmdl import (
  File "C:\Users\lukeb\AppData\Roaming\Python\Python39\Scripts\ytmdl.py", line 22, in <module>
    from ytmdl import (
ImportError: cannot import name 'dir' from partially initialized module 'ytmdl' (most likely due to a circular import) (C:\Users\lukeb\AppData\Roaming\Python\Python39\Scripts\ytmdl.py)
</pre>

I assume this happens because `ytmdl` is now in the path and tries to import itself.

**Comment by deepjyoti30** [comment]
@Vresod Yeah the circular import error is happening because now the `ytmdl.py` is conflicting with the `ytmdl` package.

Did you get the above error when you ran `ytmdl`? or did it happen when running `python ytmdl.py`?

**Comment by Vresod** [comment]
I got it when I ran `ytmdl`.

**Comment by hemish04082005** [comment]
This seems to be an issue with windows handling python generated binaries. I have encountered the same for many more projects on github. The solution seems to run the script in wsl (Windows Subsystem for Linux) environment. It works like a charm in that

**Comment by deepjyoti30** [comment]
@hemish04082005 Thanks for the suggestion. WSL is a nice solution because `ytmdl` runs flawlessly on Linux. However, adding support for Windows is one of the things I wanted to do so that the end user can just set it up without setting up anything else.

This error is very weird because I personally do not face it.

**Comment by hemish04082005** [comment]
@deepjyoti30 I had the same issue, so ran it straight in WSL.

**Comment by Vresod** [comment]
Confirmed for 2021.08.01

**Comment by hemish04082005** [comment]
Actually, if it is run with git-bash instead of powershell or cmd, then it works correctly as it should work, maybe there is some component using *nix shells

**Comment by Catwaiix** [comment]
It can run on plain cmd too. You just have to prepend `python` before calling `ytmdl`.
![](https://i.imgur.com/UBEg3UL.png)
[Winpython64-3.8.10.0dot on Windows 7 running YTMDL 2021.08.01 just fine](https://i.imgur.com/UBEg3UL.png)

**Comment by Vresod** [comment]
> 
> 
> Actually, if it is run with git-bash instead of powershell or cmd, then it works correctly as it should work, maybe there is some component using *nix shells

Can't reproduce,
![image](https://user-images.githubusercontent.com/40863375/130709854-0f32a48f-87ce-4003-a261-ba179f2f0499.png)

**Comment by deepjyoti30** [comment]
@MentalBlood Can you confirm this issue get's fixed with the renaming of the file?

The batch script was adapted from some other famous python apps that were doing that when I was looking for a solution and that was the one that actually seemed to work.

**Comment by Vresod** [comment]
Confirmed for Python 3.10, more importantly it happens on a "new" python install, not sure if that changes anything

**Comment by Vresod** [comment]
As an added note, another workaround is copying the plain `ytmdl` file to `site-packages\ytmdl\__main__.py` works to make it run with `python -m ytmdl`

**Comment by deepjyoti30** [comment]
@Vresod Does the `ytmdl` command work by itself when you rename the `ytmdl` file to `__main__.py` and put it in the package directory?

If it **does** work that way, I can make changes to the way ytmdl is packaged for Windows systems and get rid of this error altogether.

**Comment by Vresod** [comment]
Somehow the issue gets solved when installing from source? Not a clue why.
