### ISSUE TITLE
Consider removing links to and mentions of copyrighted music to avoid DMCA takedown of the project

### ISSUE THREAD

**Issue by leventerevesz** [deepjyoti30/ytmdl#181]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description

In November 2020 youtube-dl received a DMCA takedown request and was taken down from GitHub (temporarily) because it used copyrighted songs in its tests ([see an article here](https://www.eff.org/deeplinks/2020/11/riaa-abuses-dmca-take-down-popular-tool-downloading-online-video)).

I recommend removing all mentions of copyrighted music from this repository, e.g. examples in the README. Also remove all youtube links of copyrighted material from docstrings. Replacing them with royalty free alternatives may be a good solution.

**Comment by deepjyoti30** [comment]
@leventerevesz Thanks for raising the issue. I am aware about what happened to `youtube-dl`. I think now would be a good time to remove all the mentions.

I will take a look at the source to see mentions. I wanted to do this way back but got caught up with other work.

**Comment by deepjyoti30** [comment]
@leventerevesz Just updated the wiki, README and some stuff in the source to use non copyright music.

If there's anywhere else you think there's a copyrighted song being used, please point that out. Also thanks for the issue!

**Comment by leventerevesz** [comment]
I think we're good, no more problematic strings left in the repo.
