### ISSUE TITLE
Add an option to use youtube-dl --download-archive

### ISSUE THREAD

**Issue by Diridibindy** [deepjyoti30/ytmdl#183]
# Feature Request

## Checklist

- [•] I've searched the bugtracker for similar feature requests including closed ones.
- [•] I will add the enhancement label to the issue.

## Description

Add an option to use 

`youtube-dl --download-archive
`

From the manpage

`Download only videos not listed in the archive file. Record the IDs of all downloaded videos in it.`

It will be especially useful for people with large playlists.

**Comment by deepjyoti30** [comment]
@Roman-Os I am not exactly familiar with that flag but does it work like a _skip_ list?

So basically the user will pass a list with a few `videoID's` and while downloading a playlist if a `videoId` is on that list, that song is supposed to be skipped?

**Comment by Roman-Os** [comment]
> @Roman-Os I am not exactly familiar with that flag but does it work like a _skip_ list?
> 
> So basically the user will pass a list with a few `videoID's` and while downloading a playlist if a `videoId` is on that list, that song is supposed to be skipped?

Exactly. It isn't the best solution for checking whether the song is already downloaded, but it is good enough.

**Comment by deepjyoti30** [comment]
@Diridibindy You can test the feature by pulling the latest commits.

**Comment by Diridibindy** [comment]
I tested it and I can't seem to get it to work. The archive file stays empty at all times.

**Comment by deepjyoti30** [comment]
@Diridibindy I think there was a misunderstanding. I thought that the file would be just one way edited. I didn't know that the app is supposed to update it with the downloaded video ID's. I will make those changes!

**Comment by Diridibindy** [comment]
Sorry about the miscommunication on my part. That is indeed how I meant it should work. If that works on your part then you can consider the issue closed. I can't really test it myself right now
