### ISSUE TITLE
Specify a YouTube URL

### ISSUE THREAD

**Issue by mehalter** [deepjyoti30/ytmdl#2]
In the picture included in the README, it shows the YouTube URL being inputted. Add a flag to allow for this kind of interaction, like maybe `-u URL`.

**Comment by deepjyoti30** [comment]
Sorry. Had that in the intial version. Later i changed it to just the song name. I thought its easier to simply put the song name. Anyways, will try to add a flag.

**Comment by deepjyoti30** [comment]
Option added.
