### ISSUE TITLE
Consider requiring python3 in setup.py

### ISSUE THREAD

**Issue by qubidt** [deepjyoti30/ytmdl#20]
It might be a good idea to add [`python-requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to the `setup.py` to prevent people from [accidentally installing the script on non-supported python versions](https://www.reddit.com/r/commandline/comments/dwlvl4/ytmdl_download_songs_with_metadata_directly_from/f7l4b15/)

**Comment by deepjyoti30** [comment]
I'll add this in the next release.

**Comment by deepjyoti30** [comment]
I've pushed it to master, will surely be added in the next release.
