### ISSUE TITLE
More options for playlist metadata

### ISSUE THREAD

**Issue by kajus-park** [deepjyoti30/ytmdl#200]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
While downloading playlists I sometimes cannot find a song in the selection for the metadata.
Currently I think I have to choose one song to proceed even if the correct choice is not available.
I would appreciate a solution for that. There are two options that would be great to have as a choice during the metadata selection.

Describe the feature
1) skip
While selecting the metadata, there could be the option to skip the song. This would allow to continue without adding a wrongly tagged song.
2) ID
While selecting metadata, there could be the option to provide the ID of the song and apply the metadata from that.

**Comment by deepjyoti30** [comment]
@kajus-park You can skip the metadata of a song by entering `-1` when you are asked to select the metadata for a song.

Also, there are features like `on-error` which tells ytmdl what to do if an error occurs, it accpets options like `do nothing, skip that song` etc.

**Comment by deepjyoti30** [comment]
You can check the `ON_META_ERROR` flag of the config or the `--on-meta-error` flag of the CLI, both do the same thing.

If you set it on the config file then it will be used automatically every time the app runs.

**Comment by kajus-park** [comment]
Thanks a lot. For some reason I didn't find that.
