### ISSUE TITLE
[Documentation on the main README / FAQ entry] Does it work with videos, and does it work with age-restricted content?

### ISSUE THREAD

**Issue by rubyFeedback** [deepjyoti30/ytmdl#201]
Does it work with videos, and does it work with age-restricted content?

The reason why I am asking is because youtube-dl had issues when I tried to use it for
age-restricted content (on youtube). I used a proxy site to bypass the age-restricted
content (I am waaaaay above over-age and since Google keeps on sniffing after me
in the last ~20 years I wonder how they could ever possibly assume that I'd need 
an age-gate, unless they simply want to sniff more data).

The video question is mostly related to ytmdl seemingly focusing on songs. I use
ffmpeg to e. g. extract audio from video in general, though, so to me audio or video
is really two side of the medal - which is why I am asking here. Perhaps someone has
some time to add this to the main documentation, or a link to some other
article - it would be greatly appreciated.

**Comment by deepjyoti30** [comment]
@rubyFeedback `ytmdl` uses `youtube-dl` under the hood in order to download the songs so you'd still have the same Age restricted issues.

However, `ytmdl` allows you to pass the proxy that is passed on directly to `youtube-dl` while downloading something. You can try that flag.
