### ISSUE TITLE
after "running out of metadata options" allow the user to insert metadata manually

### ISSUE THREAD

**Issue by pietrotavares** [deepjyoti30/ytmdl#203]
# Feature Request

## Checklist

- [X] I've searched the bugtracker for similar feature requests including closed ones.
- [X] I will add the enhancement label to the issue.

## Description

If you're a little bit into [somewhat] alternative music, I'm pretty sure the following also happened to you already:
You told **ytmdl** to download an album, there's a song with a very "hard-to-scrape" (aka ordinary) title like "My Love".
After pressing `0<RET>` several times, you give up. You just can't find the metadata you want (or you've ran out of options)..
Then, you end up choosing whatever option and launch puddletag (or other software) to fix the definitely broken metadata you've just opted for. (I'm not going to talk about ALSO fixing the directories trees and file locations, I'm sure you people have been [exactly] there too..)

## Possible(?) Solution
Offer the (E) option.
'(E)' stands for "Okay, you're not giving me the metadata I wan't so let me just fill it in manually"

Thank you very much.

**Comment by deepjyoti30** [comment]
@pietrotavares There is already an option.

We have a flag named `on_meta_error` that allows you to do what you're saying. This flag can be passed for every ytmdl instance as a flag in the following way:

```sh
ytmdl --on-meta-error"manual"
```

You can also set the above field from the config to use it by default when adding metadata fails:

```config
ON_META_ERROR = "manual"
```

Moreover, I understand what you're saying about alternative music. Using the above flag plays along nicely with your requirement.

What it will do is:

- Try to find some meta matches
- Show you matches
- If the matches are not there or you chose to skip them, it will automatically ask you to enter metadata manually if you have the **on_meta_error** flag enabled.

**Comment by pietrotavares** [comment]
Damn, I totally missed that.

Thank you so much @deepjyoti30.
