### ISSUE TITLE
Missing first word when search full album

### ISSUE THREAD

**Issue by esturniolo** [deepjyoti30/ytmdl#21]
Hi!
When you search for an album, the first word is missing, so I think that can affect the search.
I'm not able to find albums with more than two words in the title.
I tried with simple quotes, double even with backticks, but didn't works.

![screenshot-20191115-16:12:29](https://user-images.githubusercontent.com/5169045/68969124-027d3a80-07c3-11ea-87dc-0ebcc53938a3.png)

![screenshot-20191115-16:19:55](https://user-images.githubusercontent.com/5169045/68969469-cac2c280-07c3-11ea-9624-bf97f773e376.png)

---

Also when I tried to search for an album with one word, it's fails.

Alice in Chains - Dirt
![screenshot-20191115-16:24:56](https://user-images.githubusercontent.com/5169045/68969749-7b30c680-07c4-11ea-9bde-526be324851d.png)

Perl Jam - Ten
![screenshot-20191115-16:25:31](https://user-images.githubusercontent.com/5169045/68969782-90a5f080-07c4-11ea-91a6-8421bb88efdb.png)

May be I'm doing something wrong?!

**Comment by deepjyoti30** [comment]
Hey @esturniolo . The app is intended to download songs only at the moment and that means when you pass the ```--album```, all it tries to do is find a song from the passed albumname.

So in your case, ytmdl is recognizing ```you gonna go my way``` as the song name and ```Are``` as the album where it will find the song from.

**Comment by esturniolo** [comment]
Ok, I understand now. May be you can add that in the --help.

Thanks

**Comment by deepjyoti30** [comment]
Made the help better in 67618bd
