### ISSUE TITLE
Skip "Do you still want to continue[y/n]" ?

### ISSUE THREAD

**Issue by DocMAX** [deepjyoti30/ytmdl#215]
Is it possible to avoid Do you still want to continue[y/n] message?

I dont get response in Telegram.

**Comment by deepjyoti30** [comment]
@DocMAX Where exactly are you getting this message? I think there's more than one place where this prompt is asked.

I would need to see the logs to know if this can be skipped.

**Comment by teackot** [comment]
Same issue. I am getting the message when, well, downloading the songs. I already downloaded them with yt-dlp, but they are in a different directory (~/Music_old/). Where do I find logs to show you?

**Comment by teackot** [comment]
PS: I moved those yt-dlp songs from ~/Music/ to ~/Music_old/

**Comment by teackot** [comment]
Ok, if I rename ~/Music_old/ folder (e. g. ~/Msc_old/), message doesn't show up. I think it searches for songs not in ~/Music, but in ~/Music*

**Comment by deepjyoti30** [comment]
@teackot It searches for the songs in `XDG` directories. I am not sure what it is in your case. I am sure the algorithm uses recursion to find if a song with the same song name is present.

You can use the `--nolocal` flag to get rid of this issue. 

This flag is pointed out in the README and also accessible through the `--help` flag of `ytmdl`.
