### ISSUE TITLE
ytmdl cannot download music with non-English characters.

### ISSUE THREAD

**Issue by Cwavs** [deepjyoti30/ytmdl#218]
# Bug report

## Checklist

- [X] I have searched for similar bugs in the issues.
- [X] I will add the bug label to this issue.

## Version Info

- Ytmdl version: 2021.11.07
- Youtube-dl version: 2021.12.17

## How Ytmdl was installed?

I installed ytmdl through pip, I did rename the file in the scripts folder because of #178 

## Console Log

```console
 ==> Logger running in DEBUG mode
 ==> Passed args: Namespace(SONG_NAME=['ashes', 'on', 'the', 'fire'], quiet=False, output_dir=None, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy=None, url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False)
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> ['ashes', 'on', 'the', 'fire']
 ==> ashes on the fire
 ==> None
 ==> Searching to see if already present in C:\Users\Cwavs\Music
 ==> proxy passed: None
 ==> Passed format: mp3
 ==> Searching Youtube for ashes on the fire
 ==> Choose One (One with [M] is verified music)
 [1] Attack on Titan Season 4 OST - Ashes on The Fire『Main Theme』 by AniMelody – Anime Music with dur 4:48
 [2] Ashes on The Fire (Extended) | Attack on Titan Season 4 by Kamui Extends with dur 13:17
 [3] Attack on Titan S4: Ashes on The Fire | EPIC VERSION by Samuel Kim Music with dur 5:32
 [4] 進撃の巨人 | Attack on Titan OST - Ashes on The Fire［Official Live］ by ぽにきゃん-Anime PONY CANYON with dur 4:29
 [5] [M] Ashes on The Fire (進撃の巨人 The Final Season Original Soundtrack) by KOHTA YAMAMOTO - Topic with dur 4:35
 [0] More results
 ==> Enter Choice (5): 5
 ==> 5
 ==> Downloading Ashes on The Fire (進撃の巨人 The Final Season Original Soundtrack) in 320kbps
Traceback (most recent call last):
  File "C:\Python39\Scripts\yt-dlm.py", line 562, in <module>
    extract_data()
  File "C:\Python39\Scripts\yt-dlm.py", line 557, in extract_data
    main(args)
  File "C:\Python39\Scripts\yt-dlm.py", line 279, in main
    path = download(link, yt_title, args)
  File "C:\Python39\lib\site-packages\ytmdl\core.py", line 109, in download
    logger.info('Downloading {}{}{} in {}{}kbps{}'.format(
  File "C:\Python39\lib\site-packages\simber\logger.py", line 366, in info
    self._write(message, args, LEVEL_NUMBER)
  File "C:\Python39\lib\site-packages\simber\logger.py", line 203, in _write
    stream.write(
  File "C:\Python39\lib\site-packages\simber\stream.py", line 138, in write
    print(_formatted_out, **params)
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 67-71: character maps to <undefined>
```

## Description
It seems that the program cannot download any music with none English characters in it.

**Comment by deepjyoti30** [comment]
@Cwavs Thanks for raising this issue. Seems like this is an issue from the `simber` library that `ytmdl` uses for logging.

**Comment by deepjyoti30** [comment]
@Cwavs Can you let me know which OS you are using?

The error seems like it is not exactly a `simber` issue but instead a font issue? I am not sure but it seems like the non english characters are not being mapped properly due to an invalid font in the system?

Also, I just reproduce the command above and the download was completed without any issues at all.

**Comment by deepjyoti30** [comment]
Okay, seems like it is Windows based on the file paths being referenced. Can you try to reproduce this issue on a Linux system?

It is possible this issue is specific to Windows.

**Comment by Cwavs** [comment]
Yeah I'm using windows 10, CMD doesn't show the Japanese text in the log, so that may be the case.

**Comment by deepjyoti30** [comment]
Okay, I see. At any case this is not an `ytmdl` issue.

I have already opened a new issue on `simber` for this but looking at the OS, I am not sure how breaking the issue is. Perhaps we can skip this for now.

If you can reproduce this on any other OS or if this is a breaking issue for you, you can report back on the simber issue that I referenced above.

**Comment by loulou310** [comment]
Did some testing, on the Windows terminal, the characters show up correctly. The issue is also on powershell, no characters and decode problem. On a debian based distro, it works, but it looks like it have some struggle to find the meta

(also sorry for reoppening this)

**Comment by deepjyoti30** [comment]
@loulou310 Just to clarify, struggle finding metadata is probably because of the metadata provider and not because of `ytmdl`. It's probably because of the language.
