### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by esturniolo** [deepjyoti30/ytmdl#22]
Hi again.
I can't find the config file.
When I run it with `-s`, ytdml asks for the song name.

![screenshot-20191115-16:36:53](https://user-images.githubusercontent.com/5169045/68970552-4e7dae80-07c6-11ea-9fca-fc8da4b987de.png)

**Comment by deepjyoti30** [comment]
Hey @esturniolo , the -s option will create the config, just that I made some last moment changes due to which we need to pass something as the song name.

You can do ```ytmdl -s ""``` in order to setup the config file.

**Comment by esturniolo** [comment]
But where the config file is stored?
Because if I execute `ytmdl -s ""` nothing happens.

**Comment by deepjyoti30** [comment]
The config file should be stored in ```~/. config```. 

If ```-s``` works, then you'll see no output but the file will be created.

**Comment by esturniolo** [comment]
Great! the file was created successfully.

Thanks!

**Comment by deepjyoti30** [comment]
Glad it worked. I'll close it now.
