### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'level_map'

### ISSUE THREAD

**Issue by markusgod** [deepjyoti30/ytmdl#220]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `unstable`

## How Ytmdl was installed?

Write here how you installed ytmdl. If it was through pip or some other way.
sudo pip install git+https://github.com/deepjyoti30/ytmdl.git@unstable

## Console Log

```console
ytmdl --level DEBUG --format opus https://music.youtube.com/playlist?list=PL6sYHytyKN2-X93TurF3JptW8qSVm0DzA
 ==> Logger running in DEBUG mode 
 ==> Passed args: Namespace(SONG_NAME=['https://music.youtube.com/playlist?list=PL6sYHytyKN2-X93TurF3JptW8qSVm0DzA'], quiet=False, output_dir=None, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy=None, url=None, list=None, nolocal=False, format='opus', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False) 
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> Youtube playlist passed...extracting! 
Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 569, in <module>
    extract_data()
  File "/usr/bin/ytmdl", line 532, in extract_data
    songs, playlist_name = yt.get_playlist(
  File "/usr/lib/python3.10/site-packages/ytmdl/yt.py", line 293, in get_playlist
    ) != logger.level_map["DEBUG"]
AttributeError: 'Logger' object has no attribute 'level_map'

```

## Description

ytmdl fails when trying to download https://music.youtube.com/playlist?list=PL6sYHytyKN2-X93TurF3JptW8qSVm0DzA playlist.

**Comment by deepjyoti30** [comment]
@markusgod The issue is from the `simber` package.

You need to install the `unstable` commits from `simber` as well: https://github.com/deepjyoti30/simber

Since you're using the `unstable` branch, it depends on some not released code from the `simber` source.

Installing latest commits from `simber` will fix this issue.

**Comment by mckeed** [comment]
For others who got this after updating via pip, this can be done with `python -m pip install https://github.com/deepjyoti30/simber/archive/refs/tags/0.2.4.tar.gz`
