### ISSUE TITLE
Spotify metadata using OEmbed

### ISSUE THREAD

**Issue by Ryhon0** [deepjyoti30/ytmdl#221]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description

The current spotify implementation uses the developer's key to use the Spotify API, this is probably a bad idea as it could be rate limited or blocked for whatever reason.
A safer way of doing this would be to use OEmbed. Spotify has both JSON and HTML support for OEmbed, but the HTML version exposes more information.
The JSON version can be accessed under `https://open.spotify.com/oembed`, e.g. https://open.spotify.com/oembed?url=https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT
The HTML version includes `<meta>` tags in the `<head>`.
You can extract the following information using these tags:
* Song title
* Cover image
* Author (`music:musician` links to the author spotify page, also with OEmbed)
  * Name 
  * Monthly listeners count
  * Image
* Duration (in seconds)
* Album the song is in (`music:album` links to the album page)
   * Cover image
   * All the songs in this album
   * Release year
* Position in the album
* Release date

This should be enough to replace the current implementation.
The search could potentially be replaced by using some search engine API, searching for `site:open.spotify.com/track/ ` + the name of searched song should return a page for it

**Comment by deepjyoti30** [comment]
The `oembed` approach looks real nice in terms of getting the metadata but I am a bit skeptical about the search engine part.

Can you elaborate what you mean by using a search engine API? Something like using Google's API to search google with the `site` flag enabled with the song name?

**Comment by Ryhon0** [comment]
The `site:` filter will only return results with the specified domain and path, It is supported by all of the major search engines. Following this filter should be the author's name and the song name, this should return only Spotify pages containing the author's name and song name. Putting them in quotes would make sure the words are in the correct order.
An example query would look something like this:
`site:open.spotify.com/track/ "Rick Astley" - "Never Gonna Give You Up"`.  
Putting it in any search engine should return a link to the Spotify page for this song.
I don't know if there are any search engines that allow use of their APIs without an account or without rate limits though. You'd probably have to embed the API key in the source code or create some sort of proxy.
As a last resort scraping the search engine pages for any `<a>` tags could work and probably won't break with layout updates, but some search engines, like Google sometimes require you to complete a captcha if they detect something suspicious

**Comment by deepjyoti30** [comment]
@Ryhon0 You see using the search engine API with a key or scraping it becomes a concern. All this just for one metadata provider seems like overkill considering the only downside to the current implementation is a rate limit which might show up again while using a search engines API with an API key.

**Comment by Ryhon0** [comment]
Just implementing the oembed reader would probably reduce the stress on the API. No idea what is the ratio of searches to direct downloads, I assume most people use direct download, leaving plenty of API calls for the search.
If the API becomes limited, packagers probably could provide their own keys, splitting the load.

**Comment by deepjyoti30** [comment]
@Ryhon0 Thanks for the suggestion and the explanation, however, it seems like a lot of work just to support one metadata provider. I don't see any issue with the current approach. In case the scenario actually happens to a few users where their key gets rate limited and they are unable to use `ytmdl` productively, I can reconsider this addition.

Though as of now, it just feels like a lot of work for a small addition to the various other metadata providers that `ytmdl` already supports.

I will close the issue for now, will reopen if the above scenario is actually faced by an user while using `ytmdl`.
