### ISSUE TITLE
Gentoo Ebuild support for `ytmdl` is outdated.

### ISSUE THREAD

**Issue by Ap0them** [deepjyoti30/ytmdl#222]
This isn't really a bug so I didn't submit a bug report but it should be brought to your attention that the Ebuild for gentoo is completely shot, making installation impossible, I'm not sure exactly who maintains it but it will not work until the ebuild is re-written

**Comment by deepjyoti30** [comment]
@xgqt had added support for Gentoo. I can see that the support was added way back and it seems like it has not been updated in a while.

@xgqt if you can, please consider letting us know if you'd be able to update it? We might have to drop support for Gentoo builds unless some other maintainer wants to pick it up?

**Comment by deepjyoti30** [comment]
I am adding the `help-wanted` flag in case any gentoo maintainer would like to pick the native repo and update it!

**Comment by xgqt** [comment]
Hi!

Yes, I stopped maintaining YTMDL in `src_prepare-overlay` long time ago, BUT I am willing to come back to it now.
Nevertheless it would be good to have some help from other Gentoo devs and proxy maintainers who are interested in YTMDL as it requires a lot of dependencies that are not yet packaged in the official Gentoo repository.

**Comment by xgqt** [comment]
The ytmdl branch holds current efforts to add ytmdl to ::gentoo

https://gitlab.com/xgqt/gentoo-private/-/commits/ytmdl

**Comment by Ap0them** [comment]
I'm sorry, I don't have the know-how for maintaining an ebuild now, I could learn it potentially. 

It's up to you and @xgqt but I think the help wanted tag and mentioning it's deprecated is the best decision right now

**Comment by deepjyoti30** [comment]
@xgqt Thanks for the update. Will keep this issue open with the `help-wanted` flag. Meanwhile, if you are successful in fixing the issues and updating `ytmdl` let me know!

**Comment by xgqt** [comment]
> Btw, did you update the dependency of youtube-dl to ytdl?

Yes, if you mean `yt-dlp`, in Gentoo this is called `net-misc/yt-dlp`.

> @Ap0them You can test the latest version from gentoo and report back here in case there are issues. I will close the issue shortly.

Any bugs supposed to be with Gentoo should be then reported on the Gentoo bugzilla: https://bugs.gentoo.org/

**Comment by deepjyoti30** [comment]
Cool @xgqt thanks for confirming. Closing the issue as its fixed.
