### ISSUE TITLE
Add support for quitting metadata fetch

### ISSUE THREAD

**Issue by ZXY-CC-3ag13** [deepjyoti30/ytmdl#224]
# Feature Request

## Checklist

- [ ] Add support for quitting metadata fetch

## Description

When choosing niche songs, there is a point when they don't have metadata, but you can't opt out of choosing it from selection area and are forced to choose one metadata which is inaccurate or are forced to quit (Ctrl+C)

**Comment by deepjyoti30** [comment]
You can do that by entering the choice as `-1` when the metadata is shown.

I guess there should be a print indicating that, will add that in the next release!

Moreover, in order to get rid of unseen metadata errors you can use the `--on-meta-error` flag with `skip` value.

**Comment by deepjyoti30** [comment]
@ZXY-CC-3ag13 I just cross checked, the message is already shown there indicating that `-1` will be considered as option to quit metadata. I am closing this issue!
