### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by mdotgru** [deepjyoti30/ytmdl#225]
# Bug report

## Checklist

- [X] I have searched for similar bugs in the issues.
- [X] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2022.03.16`
- Youtube-dl version: I don't seem to have it installed, but it seems to work without for most of the clips

## How Ytmdl was installed?

pip

## Console Log

==> https://www.youtube.com/watch?v=dcxsheROd3E: is unauthorized 
Traceback (most recent call last):
  File "/var/miniconda3/bin/ytmdl", line 8, in <module>
    sys.exit(entry())
  File "/var/miniconda3/lib/python3.9/site-packages/ytmdl/main.py", line 582, in entry
    extract_data()
  File "/var/miniconda3/lib/python3.9/site-packages/ytmdl/main.py", line 575, in extract_data
    main(args)
  File "/var/miniconda3/lib/python3.9/site-packages/ytmdl/main.py", line 267, in main
    link, yt_title = search(song_name=song_name, args=args)
TypeError: cannot unpack non-iterable NoneType object

## Description

In some cases for specific youtube clips I get this issue and everything stops despite the --ignore-errors flag being used.
It seems that, if the playlist (youtube playlist, not own list) includes clips that were deleted by Youtube, ytmdl breaks down instead of ignoring them and continuing.

**Comment by deepjyoti30** [comment]
@mdotgru Thanks for reporting the issue, seems like `ignore-errors` is not working as expected. I will take a look into that.

The unauthorized errors shows up when either the video is deleted or is not accessible in the region.

**Comment by deepjyoti30** [comment]
@mdotgru I am unable to reproduce this issue. As I can see, the `--ignore-errors` flag is working fine for me, could you provide some more inputs on this?

Perhaps the playlist that you are using? I tried with some videos that are not available in my region but they don't make the server crash in my case.

Another weird thing, the errors are indicating a line number but those lines are just debug log lines which cannot be crashing the program. Is it possible that you have multiple versions of `ytmdl` installed and they might be conflicting?

I see that you have shared the version you are using as the latest one but the line numbers indicate that it is probably not the latest version which leads me the believe you might have multiple versions of `ytmdl` installed that are possibly conflicting. This would also explain why the `--ignore-errors` flag is being ignored in your case.
