### ISSUE TITLE
Add support for other language characters.

### ISSUE THREAD

**Issue by Vyexk** [deepjyoti30/ytmdl#228]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 32-38: character maps to <undefined>

When I try to download a song with Japanese characters

**Comment by deepjyoti30** [comment]
@Vyexk Did you get the issue fixed?

**Comment by Vyexk** [comment]
I used --skip-meta and the error no longer came out, for now I add the metadata with another app

**Comment by Vyexk** [comment]
I used --skip-meta and the error no longer came out, for now I add the metadata with another app

**Comment by Vyexk** [comment]
The error appears when trying to download this list:

https://music.youtube.com/playlist?list=PLn9jEDhOKnnAFuVcLAJI_TlarmgYs6rH6&feature=share
