### ISSUE TITLE
Error after installing from AUR - itunespy and bs4 not installed

### ISSUE THREAD

**Issue by TheNetJedi** [deepjyoti30/ytmdl#23]
Installing from AUR doesn't automatically install itunespy and bs4, had to install them manually

**Comment by deepjyoti30** [comment]
Hey @TheNetJedi ```itunespy``` is not available in AUR so I updated the README to let people manually install it but I think ```bs4``` should be installed by ```python-beautifulsoup4``` which is a dependency.

**Comment by TheNetJedi** [comment]
@deepjyoti30 I installed `bs4`  using `pip install bs4`

Is it possible for you to add the same stuff from README to the installation script, so that after installing `ytmdl` it says that the user will have to install `itunespy` manually?

**Comment by deepjyoti30** [comment]
@TheNetJedi Yes, I will updated the PKGBUILD of AUR for that but I really think you need not have installed bs4 again. Are you sure you didn't get some mirror error or something?

**Comment by TheNetJedi** [comment]
I guess I got that "error" while installing `itunespy`, and I don't think it actually effected `ytmdl`.

My bad.

![image](https://user-images.githubusercontent.com/35243383/68988407-e29a5500-085c-11ea-857d-6dcad55015c9.png)

**Comment by deepjyoti30** [comment]
Okay, I'll update the AUR pkg with the instructions to install itunespy, thanks for the heads up.

**Comment by deepjyoti30** [comment]
@TheNetJedi Updated the PKGBUILD, after installation from AUR you will be asked to install itunespy. I'll close the issue now.
