### ISSUE TITLE
Make a music metadata retriever no downloader.

### ISSUE THREAD

**Issue by Rexadev** [deepjyoti30/ytmdl#235]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description

I want musicbrainz picard but with  iTunes, Spotify, LastFM, Deezer. No downloader just the metadata viewer

**Comment by deepjyoti30** [comment]
@Rexadev I don't understand the request. Could you explain a bit more? I am not sure what you mean by metadata retriever?

Do you mean something like a tool that shows you metadata from various sites and just that, nothing else?

**Comment by Rexadev** [comment]
> Do you mean something like a tool that shows you metadata from various sites and just that, nothing else?

Yes, [ytmdl](https://github.com/deepjyoti30/ytmdl) without downloader. The program asks for a song name shows metadata from different services
Something like https://picard.musicbrainz.org/

**Comment by deepjyoti30** [comment]
@Rexadev There have been similar requests in the past. Mostly to create a tagger that would automatically scan songs, apply tags.

However, creating a tool just to get metadata would not be under the scope of `ytmdl`. `ytmdl` already does have code that does exactly what you're asking for but altering the behaviour of a tool that is supposed to be able to extract and then add meta is not a good idea.

You can always pick up the code from `ytmdl` and make something of your own. You wouldn't even have to do much, just write a script that utilizes pre-defined methods from `ytmdl` and it will work.

I have done something similar for the `ytmdl` web-api that provides an endpoint to search metadata based on a passed name but that's as much as I can help you here.
