### ISSUE TITLE
Pipe Symbol "|" in a Song Name causes it to crash

### ISSUE THREAD

**Issue by wh0th3h3llam1** [deepjyoti30/ytmdl#236]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2022.03.16`
- Youtube-dl version: `Not Installed`

## How Ytmdl was installed?

Installed on `Windows 10` using `pip`
Python Version: `3.10.2`
Pip Version: `pip 22.0.3`

## Console Log

```console
> ytmdl https://www.youtube.com/watch?v=GADlWyHaMmI --level DEBUG
 ==> Logger running in DEBUG mode
 ==> Passed args: Namespace(SONG_NAME=['https://www.youtube.com/watch?v=GADlWyHaMmI'], quiet=False, output_dir=None, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy=None, url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, ytdl_config=None, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False)
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> ['https://www.youtube.com/watch?v=GADlWyHaMmI']
 ==> https://www.youtube.com/watch?v=GADlWyHaMmI
 ==> None
 ==> Searching to see if already present in C:\Users\Root\Music
 ==> proxy passed: None
 ==> Passed format: mp3
 ==> Searching Youtube for https://www.youtube.com/watch?v=GADlWyHaMmI
 ==> Choose One (One with [M] is verified music)
 [1] Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill by Music Vibes Zone with dur 4:29
 [2] Gandhari Dance Cover | vaishnavi | Full song dance | Keerthy Suresh | Pawan CH | Suddala Ashok Teja by vaishnavi varnika with dur 3:16
 ==> Enter Choice (1): 1
 ==> 1
 ==> Downloading Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill in 320kbps
 ==> Saving the files to: C:\Users\Root\.cache\ytmdl
 ==> C:\Users\Root\.cache\ytmdl\Coke#Studio#|#Season#14#|#Pasoori#|#Ali#Sethi#x#Shae#Gill.mp3
 ==> Enabling progress hook.
 ==> Passed value for no_progress: False
[youtube] GADlWyHaMmI: Downloading webpage
[youtube] GADlWyHaMmI: Downloading android player API JSON
[info] GADlWyHaMmI: Downloading 1 format(s): 251
[download] Destination: C:\Users\Root\.cache\ytmdl\Coke#Studio###Season#14###Pasoori###Ali#Sethi#x#Shae#Gill.mp3
[download] 100% of 4.45MiB in 00:00
 ==> Downloaded!
[youtube] GADlWyHaMmI: Downloading webpage
[youtube] GADlWyHaMmI: Downloading android player API JSON
 ==> [{}]
 ==> song_name:  Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill  song_meta:  https://www.youtube.com/watch?v=GADlWyHaMmI
 ==> None
 ==> None:None
 ==> Skip Meta: False
 ==> Getting song data for https://www.youtube.com/watch?v=GADlWyHaMmI...
 ==> Searching metadata with itunes
 ==> No results found with the keyword https://www.youtube.com/watch?v=GADlWyHaMmI
 ==> Something went wrong with iTunes. The program will continue withthe other providers. Please check '[C:\Users\Root\.cache\ytmdl\logs\log.cat]' for more details.
 ==> Searching metadata with gaana
 ==> Searching metadata with spotify
 ==> Using US for Spotify country
 ==> ext: mp3
 ==> Moving to: C:\Users\Root\Music
 ==> [Errno 22] Invalid argument: 'C:\\Users\\Root\\.cache\\ytmdl\\Coke#Studio#|#Season#14#|#Pasoori#|#Ali#Sethi#x#Shae#Gill.mp3_new.mp3'
 ==> No metadata found for `https://www.youtube.com/watch?v=GADlWyHaMmI` . Pass `--ignore-errors` or `on-meta-error` to ignore this.
```

## Description

If there's a pipe symbol `|` in a song name, it will download it, but will cause an error while moving it to current directory.
>   ==> [Errno 22] Invalid argument: 'C:\\Users\\Root\\.cache\\ytmdl\\Coke#Studio#|#Season#14#|#Pasoori#|#Ali#Sethi#x#Shae#Gill.mp3_new.mp3'

#### Sample URL

> [https://www.youtube.com/watch?v=GADlWyHaMmI](https://www.youtube.com/watch?v=GADlWyHaMmI)

![image](https://user-images.githubusercontent.com/48444630/177509361-767dd09e-67b2-4019-9322-1fd848b00820.png)

#### Sample URL

> [https://www.youtube.com/watch?v=7ypyKG4Iu5k](https://www.youtube.com/watch?v=7ypyKG4Iu5k)

![image](https://user-images.githubusercontent.com/48444630/177509505-3061d7eb-6691-444a-bd0b-39ef838cccec.png)

**Comment by deepjyoti30** [comment]
@wh0th3h3llam1 Seems like an Windows specific issue. I just tried the song you shared and it downloaded fine without any issues and was moved properly as well.

Could you share the details of the OS you are using? Looking at the pictures, I am assuming it is Windows?!

Will have to reproduce the issue on Windows to debug it better.

**Comment by wh0th3h3llam1** [comment]
@deepjyoti30 Yes, you are correct, I'm on Windows 10

### OS Specifications
```
Edition	Windows 10 Home Single Language
Version	21H2
Installed on	‎13-‎02-‎2022
OS build	19044.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

**Comment by wh0th3h3llam1** [comment]
I found a similar issue when Quote `"` is in the song name. I tried a [song](https://www.youtube.com/watch?v=iKopExw_3Zg) with only parenthesis `()` and its working fine.

> Sample URL: [https://www.youtube.com/watch?v=9Cp-hNvSWZs](https://www.youtube.com/watch?v=9Cp-hNvSWZs)

![image](https://user-images.githubusercontent.com/48444630/178094217-95ed86ad-2ef4-468e-abb7-fbc4a7ca39b5.png)

**Comment by deepjyoti30** [comment]
@wh0th3h3llam1 Thanks for confirming. Seems like these characters are not properly blacklisted for Windows. For Linux, this was an issue reported way back and was taken care of way back.
