### ISSUE TITLE
Want a new feature added? Comment on this issue to make a request.

### ISSUE THREAD

**Issue by deepjyoti30** [deepjyoti30/ytmdl#24]
## Hey guys, tell me what you'd like me to add in the next release.

I'd love to do my best and add features for everyone.

**Comment by ELChris414** [comment]
It's a common phenomenon with greek songs that on youtube they're added with greek characters but on iTunes/Spotify/etc. they're added with english characters. Please give us the option to give a different input for metadata (like a -1 in the option or maybe a new flag)

**Comment by deepjyoti30** [comment]
@ELChris414 I'll try to do something about that.

**Comment by deepjyoti30** [comment]
Hey @ELChris414 can you install the latest commits and try passing the songname to search metadata seperately using the ```--song``` option? Tell me if that works for you.

**Comment by ELChris414** [comment]
Hello! Sure, I'll try it. Thanks for the quick response!

**Comment by ELChris414** [comment]
I may be doing something wrong but I get an *irrelevant with this* issue:

> AttributeError: module 'ytmdl.utility' has no attribute 'is_present'

**Comment by deepjyoti30** [comment]
@ELChris414 Seems like there's some issue with your installation, can you please try uninstalling and then installing the latest commits.

**Comment by ELChris414** [comment]
Had to also change where I get youtube-dl from as my current installation didn't provide the latest update, but, after all, it worked great! Thank you so much man! You're awesome. Here's the exact example that made me send this suggestion:
![E6ACFDD8-A473-42F4-BC46-E282D4AE673E](https://user-images.githubusercontent.com/8685248/70258976-e6ebcb00-1795-11ea-97c0-69ace38c03e4.png)

**Comment by ELChris414** [comment]
When naming the file one time it used the metadata name and the other it didn't rename it I've just noticed

**Comment by ELChris414** [comment]
Album downloading would be an interesting feature. Won't work with all albums, but for the ones it does, it will be perfect

**Comment by deepjyoti30** [comment]
Yeah but that will be a lot of work, you know. For any album we would've to extract all the songs from either Itunes or Gaana and then download the songs then.

I might add it sometime later though. But the reason behind adding the ```--list``` option was to let users download a whole album.

If you want it that bad, raise a different issue and I'll sure give it a try.

**Comment by ELChris414** [comment]
Was just an idea I had, not that important or anything. Lists do work fine!

**Comment by AyushRawal** [comment]
It would have been great if we can just play songs directly instead of downloading them.....
Mpv works well with youtube-dl and has --no-video option
I wrote a small script that does the same.....
Hope u consider it

**Comment by deepjyoti30** [comment]
@AyushRawal I might consider adding an option to stream directly after selecting the app rather than downloading.

**Comment by Samyocord** [comment]
Maybe add an option for the user to select wheter to download from YouTube Music or YouTube.

**Comment by deepjyoti30** [comment]
@AyushRawal Why don't you try [playx](https://github.com/NISH1001/playx)? Adding a stream option to ```ytmdl``` would be making it work like ```playx``` so I'll skip that for a while.

**Comment by AyushRawal** [comment]
@deepjyoti30 It looks so great ... I am quite interested to try this out ...  Thanks a lot

**Comment by deepjyoti30** [comment]
@AyushRawal I've been contributing to it for a long time now. Do raise issues in case you face any. [Nishan](https://github.com/NISH1001) and I are always glad to fix them.

**Comment by AllMight420** [comment]
64-bit Support

**Comment by deepjyoti30** [comment]
@AllMight420 What exactly do you mean by 64 bit support??

**Comment by AllMight420** [comment]
Well i have a win 10 64-bit. When i installed ytmdl, the ytmdl file in the
bin folder had no extension. So i added .exe and when i tried to run it.
this is what happens.

**Comment by deepjyoti30** [comment]
@AllMight420 Oh, I see you want support for Windows. I did thought that I will keep support for Windows but as I added support it became more harder.

Also, I don't use Windows myself so it's hard for me to keep support, I'd really need some testers for that. Anyway I'll look into it if possible.

**Comment by AllMight420** [comment]
appreciate it

**Comment by AllMight420** [comment]
i tried it on kali linux and this error popped up
Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 19, in <module>
    from ytmdl import (
  File "/usr/local/lib/python2.7/dist-packages/ytmdl/song.py", line 51
    print(Fore.LIGHTMAGENTA_EX, end='')

**Comment by deepjyoti30** [comment]
@AllMight420  Can you please open a new issue for the Kali linux error and also give me a proper traceback?!

**Comment by AllMight420** [comment]
> @AllMight420 Can you please open a new issue for the Kali linux error and also give me a proper traceback?!

sry my bad. it wasnt installed properly

**Comment by EvilSpark** [comment]
Can you add an option to download a playlist by giving URL? Since adding metadata through youtube-dl still leaves lots of stuff out of place

**Comment by deepjyoti30** [comment]
@EvilSpark Sounds good. I think that would be a neat addition, I'll try to add it in the next release.

**Comment by deepjyoti30** [comment]
@EvilSpark I have added the functionality to download from playlists, you can try out the latest commits and raise an issue if you find any bugs.

**Comment by EvilSpark** [comment]
@deepjyoti30 You should also add `--ignore-errors` to playlist section since it usually stops midway if some video is unavailable.

Thanks for this feature tho. :+1:

**Comment by Tindome** [comment]
# Create config file on first launch
> i have to create the dir manually to be able to set the song_dir

# Add the ability to set a param for cache location : i prefer not to use ./home 

# Rework on check for youtube-dl
> i have to disable it (i use virtual env) else it says youtube-dl was not detected

**Comment by lebanni** [comment]
Can you add support for aac/m4a format ?

**Comment by deepjyoti30** [comment]
@lebanni I will probably have to look for that.

@Tindome Those seem like good additions but I would consider the second one as a bug. Please gimme some logs on the error part. 

Regarding the config file, I can work on that but I would really appreciate if you could explain a bit more about it.

I will open a new issue regarding the above.

**Comment by deepjyoti30** [comment]
Seems like it's better to let users create a new issue tagged as a feature request. This issue seems to be overwhelmed with new requests. Closing it for the same reason.

## Please create a new issue with [Feature] in the title
