### ISSUE TITLE
One music breaks to many music files

### ISSUE THREAD

**Issue by sgon00** [deepjyoti30/ytmdl#241]
# Bug report

## OS

debian 11.4

## How Ytmdl was installed?

```
pip install ytmdl
```

## Description

```
ytmdl https://music.youtube.com/watch?v=gd4aqZxa1Fc
```

It downloads many small music mp3 files instead of one. But it's only one music.

**Comment by deepjyoti30** [comment]
@sgon00 If you take a look at the above songs Youtube page [here](https://www.youtube.com/watch?v=gd4aqZxa1Fc) you'll see that the song actually has chapters and `ytmdl` supports parsing chapters separately. That behavior is taking place in your case and is leading to multiple files where each file is one chapter.

You can use the `--ignore-chapters` flag with the above command to stop this behavior and download to one file. The above `ytmdl` command would translate to:

```sh
ytmdl https://music.youtube.com/watch?v=gd4aqZxa1Fc --ignore-chapters
```

**Comment by sgon00** [comment]
@deepjyoti30 thank you very much for the answer. It works.
