### ISSUE TITLE
Save audio files without transcoding. 

### ISSUE THREAD

**Issue by berinaniesh** [deepjyoti30/ytmdl#250]
# Feature Request

## Checklist

- [x] I will add the enhancement label to the issue.
- [x] I've searched the bugtracker for similar feature requests including closed ones.

## Description
Some of us don't mind keeping the  audio as it is, without re-encoding with ffmpeg to prevent [Generation Loss](https://en.wikipedia.org/wiki/Generation_loss#Digital_generation_loss). In youtube-dl or yt-dlp, we can get opus audio (just extraction, no transcoding) with the flags -f 251 -x. 
In ytmdl, even if the format of opus is given, it seems ytmdl re-encodes the file, which will result in Generation Loss. I understand the loss is minor and we probably can't even notice it and I am obsessing over a small thing, but it would be nice to have an option to save the audio without transcoding.

**Comment by deepjyoti30** [comment]
@berinaniesh I think this is a valid enhancement and since `youtube-dl` supports it, `ytmdl` should as well. I will look into this request to see if this will be possible with the current architecture of `ytmdl`.

Thanks for raising the issue!

**Comment by deepjyoti30** [comment]
@berinaniesh This is now possible with a new flag added named `--dont-transcode`. Added in this commit: 3cf1a36
