### ISSUE TITLE
ytmdl outputs lower quality than yt-dlp

### ISSUE THREAD

**Issue by manstie** [deepjyoti30/ytmdl#261]
# Bug report

## Version Info

- ytmdl version: `2023.2.28`
- yt-dlp version: `2023.2.17`

## How Ytmdl was installed?

Windows - pip

## Description

Using the `m4a` format option produces lower quality (reduced frequency range) than `opus` and `mp3`. The ideal range is up to 20khz.

![image](https://user-images.githubusercontent.com/12475567/222141554-1ccdce56-10c0-4490-9e4c-4f17a7524e29.png)

probe of m4a:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\test m4a.m4a':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf60.4.100
  Duration: 00:05:00.71, start: 0.000000, bitrate: 129 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
```
probe of mp3:
```
Input #0, mp3, from '.\test mp3.mp3':
  Metadata:
    encoder         : Lavf60.4.100
  Duration: 00:05:00.75, start: 0.025057, bitrate: 320 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc60.5.
```

Using yt-dlp does not have this affliction with the following parameters (albeit a much larger filesize):
`yt-dlp --extract-audio --audio-format m4a [URL]`

Opus files are also lower quality:

probe from ytmdl
```
Input #0, ogg, from '.\song.opus':
  Duration: 00:04:33.02, start: 0.007500, bitrate: 98 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
```

probe from yt-dlp
```
Input #0, ogg, from '.\song.opus':
  Duration: 00:04:33.03, start: 0.007500, bitrate: 127 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
```

**Comment by deepjyoti30** [comment]
@manstie Thanks for opening this issue, that's some nice insights. I will have to look into the current implementation to see how we can improve this. The difference between `yt-dlp` and `ytmdl` files are that we do the conversion separately (though both uses `ffmpeg` under the hood).
