### ISSUE TITLE
ytmdl --list YOUTUBE_PLAYLIST_URL  ====> YOUTUBE_PLAYLIST_URL is empty

### ISSUE THREAD

**Issue by toy-k** [deepjyoti30/ytmdl#280]
# Question

## Checklist

- [ㅇ ] I've looked through the README and the WiKi for something similar.
- [ ] I tried talking with the developer on the Telegram support group.

## Question

Write question here

few months ago, I downloaded YouTube playlist mp3 files to use YTMDL.
but yesterday day when I tried to download files, it didn't work. 
on terminal I typed like this. 

```
ytmdl --list https://www.youtube.com/watch?v=yIvXuXOTEPA&list=RDMM&start_radio=1
```
after input command, it showed
```
==> https://www.youtube.com/watch?v=yIvXuXOTEPA&list=RDMM&start_radio=1: is empty
```

I don't know how to solve this problem... please I hope to listen your idea:)

**Comment by deepjyoti30** [comment]
@toy-k Were you able to fix the issue as you closed it?
