### ISSUE TITLE
Allow overriding ytmdl config file every run

### ISSUE THREAD

**Issue by hariprasanths** [deepjyoti30/ytmdl#282]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
Currently all the ytmdl instances use a global config - ~/.config/ytmdl. Support for overriding the config every run can help in automating multiple configurations with different providers/dynamic directories.

Something like the following
ytmdl --ytdml-config ~/.config/ytmdl/spotifyConfig --url <>

**Comment by deepjyoti30** [comment]
@hariprasanths Thanks for the request. I have seen this request come up a few while back as well, let me see if this can be done.

**Comment by deepjyoti30** [comment]
@hariprasanths I checked on this and it will be hard to support that behaviour based on the current architecture of config in `ytmdl`. Unless I do a complete rework of how config is handled, this will not be possible.

**Comment by hariprasanths** [comment]
Will it be possible to have dynamic output paths via -o arg param? 
Or a combination of output path in dynamic path in config file? Something like this in the config file - $OutputPathFromArgs$Album$Artist

**Comment by deepjyoti30** [comment]
@hariprasanths Let me check on that. Is your use-case just to be able to pass dynamic path params from the arguments?

**Comment by hariprasanths** [comment]
I am interested in overriding the providers and passing the dynamic output path on every run. Can work with the support to pass a dynamic output path via args.

**Comment by hariprasanths** [comment]
I am getting the following error when trying to download a playlist with 600+ songs:
[Errno 24] Too many open files

Following are some the places where I think the files aren't closed:
download archive file, song's cache file, artwork file

Shall I open a new issue for this?

**Comment by deepjyoti30** [comment]
@hariprasanths Yes, a new issue is suggested.

**Comment by deepjyoti30** [comment]
@hariprasanths Support for advanced path (dynamic naming) is added and will be included in the next release.

Just a sneak peak of how it will work:

```sh
ytmdl "sundown" --output-dir "/Users/deepjyoti30/Music\$Artist->Album->Title"
```

**Comment by deepjyoti30** [comment]
@hariprasanths This is now included in the latest release!
