### ISSUE TITLE
[Premium Youtube Music] can't download premium only songs!

### ISSUE THREAD

**Issue by akhiljalagam** [deepjyoti30/ytmdl#289]
# Feature Request
Support premium users via login to download songs

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
At the moment, I am unable to download songs that are only available for premium users. Is there any temporary solution to this issue?

**Comment by deepjyoti30** [comment]
Not sure if there is. This is probably an issue with how `yt-dlp` works as `ytmdl` uses that to fetch the audio from sources like yt music. Closing as this is out of scope for `ytmdl`.
