### ISSUE TITLE
Using `ytmdl --list LIST` requires positional argument.

### ISSUE THREAD

**Issue by amirulmenjeni** [deepjyoti30/ytmdl#29]
Forgive me if this is a trivial issue, but from reading the help message it seems that `--list` option takes a list of song names separated by newline, which means whatever songs I want to download is already included in that list. Therefore, the positional argument `SONG_NAME` isn't required since it's already included in `LIST`.

**Comment by deepjyoti30** [comment]
@amirulmenjeni Yes, it is a known issue. It will sure be fixed in the next release. You can try installing the latest commits by cloning the repo and installing till then.

**Comment by deepjyoti30** [comment]
Should be fixed in the last release.
