### ISSUE TITLE
No Download Available

### ISSUE THREAD

**Issue by loveDBZ1** [deepjyoti30/ytmdl#299]
![image](https://github.com/user-attachments/assets/86643b47-c440-47be-8d68-acb5393b1002)

The website where the project is hosted displays this [See image] page when going to download a song presenting no download button or way to download.

**Comment by Shenote04** [comment]
same issue for me

**Comment by deepjyoti30** [comment]
I am aware of the issue and am investigating this.

**Comment by deepjyoti30** [comment]
It is back up. Closing the issue. Please open future issues in the web repo instead.
