### ISSUE TITLE
SONG_DIR with spaces

### ISSUE THREAD

**Issue by mehalter** [deepjyoti30/ytmdl#3]
If I have a SONG_DIR with spaces in any of the names it doesn't work and reverts back to the default. Whether or not I do an escaped space or not

Ex:
`SONG_DIR = "/home/user/Music/My Music$Artist->Album"`
and
`SONG_DIR = "/home/user/Music/My\ Music$Artist->Album"`

**Comment by deepjyoti30** [comment]
Are you sure the path is correct, i mean its already present? In case its not present the folder is changed to default. 
I am away from my computer right now but will check that ASAP 😊

**Comment by deepjyoti30** [comment]
Should be fixed now.
