### ISSUE TITLE
ffmpeg is need by ytmdl

### ISSUE THREAD

**Issue by rpesche** [deepjyoti30/ytmdl#33]
Hello !

At some point, `ytmdl` launch `ffmpeg`.

If it's not installed we get an error : `ERROR: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'`

I think we need to add a check at the very beginning of the executions, because this error apear after searching and selecting a song.

**Comment by deepjyoti30** [comment]
Thanks for the update, I've been meaning to add that.

**Comment by rpesche** [comment]
There is `youtube-dl` to :)

**Comment by deepjyoti30** [comment]
```youtube-dl``` is already a dependency so the ```setup.py``` installs it on installation.
