### ISSUE TITLE
how to use a proxy like   youtube-dl --proxy "socks5://127.0.0.1:1086" 

### ISSUE THREAD

**Issue by zronghui** [deepjyoti30/ytmdl#35]

**Comment by deepjyoti30** [comment]
@zronghui Currently there's no such option. I will surely add that option soon.

**Comment by deepjyoti30** [comment]
Hey @zronghui I added the option. Can you please try and confirm it's working on your end?

**Comment by zronghui** [comment]
> Hey @zronghui I added the option. Can you please try and confirm it's working on your end?

➜  ytmdl git:(master) ytmdl --proxy "socks5://127.0.0.1:1086/" dangerously
 ==> Searching to see if already present in /Users/zhangronghui/Music
 ==> Searching Youtube for dangerously

It just got stuck.

**Comment by deepjyoti30** [comment]
@zronghui Weird, it's working all right for me. Is it working with ```youtube-dl``` currently?

**Comment by zronghui** [comment]
@deepjyoti30  youtube-dl works

**Comment by deepjyoti30** [comment]
@zronghui Are you sure it's not a network issue? How long was it stuck for?

**Comment by zronghui** [comment]
@deepjyoti30  for 4 minutes，then I stopped it

**Comment by deepjyoti30** [comment]
@zronghui Did you try with other song names??

**Comment by zronghui** [comment]
@deepjyoti30  "money in the grave" is the same

**Comment by deepjyoti30** [comment]
Is ```ytmdl``` working without proxy?? I mean without using the proxy can you get the search results from YouTube??

**Comment by zronghui** [comment]
no, I am in china

**Comment by deepjyoti30** [comment]
Okay, I think I got the issue. I'll make some changes and tell you to test. Thanks for all the info.

**Comment by deepjyoti30** [comment]
@zronghui Hey, can you check the latest commit. It should not be stuck at least.

**Comment by zronghui** [comment]
@deepjyoti30 
➜  ytmdl git:(master) ytmdl --proxy "socks5://127.0.0.1:1086/" money in the grave
 ==> Searching to see if already present in /Users/zhangronghui/Music
 ==> Searching Youtube for money in the grave
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ytmdl/yt.py", line 119, in search
    response = requests.get(url, proxies=proxies)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    prep.url, proxies, stream, verify, cert
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 699, in merge_environment_settings
    no_proxy = proxies.get('no_proxy') if proxies is not None else None
AttributeError: 'list' object has no attribute 'get'
 ==> No song found. Please try again with a different keyword.

**Comment by deepjyoti30** [comment]
Hey @zronghui Sorry about that, should be fixed now.

**Comment by zronghui** [comment]
@deepjyoti30 Well, It stuck again.Maybe you should put this aside for the moment.And I will go to the shower.

**Comment by deepjyoti30** [comment]
@zronghui Just made a small change, can you check if it works?

**Comment by zronghui** [comment]
@deepjyoti30 
`➜  ytmdl git:(master) ytmdl --proxy "socks5://127.0.0.1:1086/" money in the grave
 ==> Searching to see if already present in /Users/zhangronghui/Music
 ==> Searching Youtube for money in the grave
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ytmdl/yt.py", line 122, in search
    response = requests.get(url, proxies=proxies)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 189, in proxy_manager_for
    **proxy_kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 47, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
 ==> No song found. Please try again with a different keyword.
➜  ytmdl git:(master) c
➜  ytmdl git:(master) pip3 install pysocks
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pysocks
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)")': /simple/pysocks/
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Installing collected packages: pysocks
Successfully installed pysocks-1.7.1
➜  ytmdl git:(master) ytmdl --proxy "socks5://127.0.0.1:1086/" money in the grave
 ==> Searching to see if already present in /Users/zhangronghui/Music
 ==> Searching Youtube for money in the grave
 ==> No song found. Please try again with a different keyword.
➜  ytmdl git:(master) ytmdl --proxy "socks5://127.0.0.1:1086/" dangerously
 ==> Searching to see if already present in /Users/zhangronghui/Music
 ==> Searching Youtube for dangerously
 ==> No song found. Please try again with a different keyword.`

**Comment by deepjyoti30** [comment]
This thing is really irritating me. Thanks for helping, I'll reply back to you ASAP

**Comment by deepjyoti30** [comment]
@zronghui Hey, can you still help in testing?? I just want to add this feature but it's hard for me to detect the bugs because I don't have a restricted network.

It'd be really helpful if you can help with that.

**Comment by deepjyoti30** [comment]
Hey @zronghui I think the previous issues we were facing regarding the proxy were probably at the download stage and since I am making the move to ```youtube-dl``` downloader, it'll be fixed now.

If you are free, I'll really appreciate if you could test the latest commits and tell me if the proxy option works and if you face bugs, if any.

**Comment by mortezadadgar** [comment]
@deepjyoti30 hey, ytmdl stuck at connecting to socks
`❯ ytmdl Sapce Oddity --format mp3 --proxy socks5://127.0.0.1:9050 --level DEBUG
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=['Sapce', 'Oddity'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy='socks5://127.0.0.1:9050', quiet=False, skip_meta=False, song=None, trim=False, url=None)
 ==>  ['Sapce', 'Oddity']
 ==>  Sapce Oddity
 ==>  Searching to see if already present in /home/morteza/Music
 ==>  proxy passed: socks5://127.0.0.1:9050
 ==>  Passed format: mp3
 ==>  Searching Youtube for Sapce Oddity
`
I can use torsocks but that error out about a missing syscall however ytmdl should be able connect to socks proxy out of the box

**Comment by deepjyoti30** [comment]
@mortezadadgar It should be able to however I wasn't able to test the feature due to no access to a proxy and when I had implemented the issue, I didn't have any testers as well.

I feel like the stuck issue might be because of the `youtube-search` module but that is just a guess, I cannot for sure, reproduce this issue.
