### ISSUE TITLE
Using a list adds spaces between title's characters

### ISSUE THREAD

**Issue by ELChris414** [deepjyoti30/ytmdl#38]
Very odd bug, but it is able to be seen from the search at youtube. It causes big issues in iTunes search.

Ex.
The Game of Love is being searched as T h e G a m e  o f  L o v e

**Comment by deepjyoti30** [comment]
@ELChris414 Thanks for the heads up, fixed it. Try the latest commit and close the issue as you like.

**Comment by ELChris414** [comment]
Working!
