### ISSUE TITLE
Renaming / Moving fails

### ISSUE THREAD

**Issue by ELChris414** [deepjyoti30/ytmdl#39]
Many times the renamed file remains in ~/.cache and you get a weird, unplayable with no metadata and youtube-dl's naming .mp3 file in ~/Music instead. Can't find what causes this but it happens really often.

**Comment by deepjyoti30** [comment]
@ELChris414 Seems like a weird issue. I haven't faced that, I would need some more details in order to fix it.

**Comment by deepjyoti30** [comment]
@ELChris414 Okay, got the issue. 

I recently moved to using the ```ffmpeg-python``` module instead of using the cli one using ```os```. So I forgot to add the part where we remove the temporary file. Fixed it in the latest commit.

Test it and close the issue if it's fixed.

**Comment by ELChris414** [comment]
File gets renamed correctly but now stays in ~/.cache/ytmdl, it isn't moved.

**Comment by deepjyoti30** [comment]
@ELChris414 Are you sure those files are not from before you installed the latest commits?

Try removing everything in the dir and then try downloading a song.

**Comment by ELChris414** [comment]
I'm testing many songs, seems like only that time something went wrong. Will close issue in some minutes

**Comment by deepjyoti30** [comment]
Cool, glad it's working for you!
