### ISSUE TITLE
Error when running python setupConfig.py

### ISSUE THREAD

**Issue by NaiCity** [deepjyoti30/ytmdl#4]
Hello there !

I have managed to clone the ytmdl from GitHub and run the subsequent commands successfully, However, when running python setupConfig.py I'm getting this error

Traceback (most recent call last):
  File "setupConfig.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib

**Comment by deepjyoti30** [comment]
Do you have python 3.4+ ? pathlib is supposed to be in your python setup.
Please upgrade your python version to the latest one or at least one that is v3.4 or more.

**Comment by NaiCity** [comment]
I have 2 versions of Python as seen below. I'm running Ubuntu 16.04 hosted
on AWS.

root@ip-172-31-26-168:/home/ubuntu# python --version
Python 2.7.12
root@ip-172-31-26-168:/home/ubuntu# python3 -V
Python 3.5.2

**Comment by deepjyoti30** [comment]
Did you run setupConfig with python3?

**Comment by NaiCity** [comment]
Yes I did, but still I got the same result. I even tried it with CentOS 7 .

**Comment by deepjyoti30** [comment]
That's a weird issue man. 
Try ```sh sudo pip install pathlib```

**Comment by NaiCity** [comment]
That runs well but then when I run python,setupConfig.py I get

Traceback (most recent call last):
  File "setupConfig.py", line 8, in <module>
    class DEFAULTS:
  File "setupConfig.py", line 12, in DEFAULTS
    HOME_DIR = str(Path.home())
AttributeError: type object 'Path' has no attribute 'home'

**Comment by deepjyoti30** [comment]
I really think this is probably because of two setups. Other users are not facing any issues. If possible can you try anywhere with just python 3 installed?

**Comment by mehalter** [comment]
I cannot get anything to run either. Both the setupConfig.py and the ytmdl.py return this error

```
Traceback (most recent call last):
  File "setupConfig.py", line 8, in <module>
    class DEFAULTS:
  File "setupConfig.py", line 24, in DEFAULTS
    CONFIG_PATH = os.path.join(Path.home(), '.config', 'ytmdl')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

**Comment by deepjyoti30** [comment]
Its weird coz i am able to use it all right.
Can you post the pathlib version?
Just run the following command and post the output
```sudo pip install pathlib```
Also which linux distro are you using?

**Comment by deepjyoti30** [comment]
@mehalter Do you have a .config folder?

**Comment by mehalter** [comment]
I do. That is a type error for join, not a problem with my folder. Also I have all the dependencies.

**Comment by deepjyoti30** [comment]
@mehalter Type following and show me the output
```sh
python
```
Then the following
```python
from pathlib import Path
print(Path.home())
```
Please post the output

**Comment by mehalter** [comment]
So I have done the pip install and it installed great. If I run `ytmdl -s` without the config folder already created I get the error `AttributeError: module 'os' has no attribute 'mkdirs'`.

**Comment by NaiCity** [comment]
@mehalter  Exactly. I'm getting this error
Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 168, in <module>
    main()
  File "/usr/local/bin/ytmdl", line 60, in main
    setupConfig.make_config()
  File "/usr/local/lib/python3.5/dist-packages/ytmdl/setupConfig.py",n make_config
    os.mkdirs(DEFAULTS.CONFIG_PATH)
AttributeError: module 'os' has no attribute 'mkdirs'

**Comment by deepjyoti30** [comment]
Sorry about that issue. I made a silly mistake. I have fixed it and it should be working all right now. Please try it.

**Comment by NaiCity** [comment]
Can you please give me the steps again please ?

**Comment by deepjyoti30** [comment]
@NaiCity Sorrry for such a late reply. Most issues are fixed now. Please try installing the latest  version by
```sudo pip install --no-cache-dir ytmdl --upgrade```
If you have any version already installed then consider uninstalling it by the followingf command
```sudo pip uninstall ytmdl```
