### ISSUE TITLE
Some songs don't have data

### ISSUE THREAD

**Issue by ELChris414** [deepjyoti30/ytmdl#41]
They exist in iTunes, but when searched for they either don't appear in any of the 70 options or give the message "No data found". How are songs searched? Maybe different data methods would be better?

Examples:
That's what I like (Bruno Mars 24K Magic)
Giorgio by Moroder (Daft Punk Random Access Memories)

**Comment by deepjyoti30** [comment]
@ELChris414  I think the ```Georgio``` song is showing up all right. Though, I did find That's what I like cause an issue. I'll try to do something about that.

**Comment by deepjyoti30** [comment]
@ELChris414 Seems like found the bug that was causing the issue, it will be fixed in the next release. 
I have already committed the changes.
