### ISSUE TITLE
Is it possible to use this as a library?

### ISSUE THREAD

**Issue by LegendL3n** [deepjyoti30/ytmdl#44]
Hi there,

I wish to use this for song downloading as a replacement to YoutubeDL, due to its tagging capabilities.
Can I integrate it in my script? (via import)

**Comment by LegendL3n** [comment]
I closed as I've skimmed through the code and found out it's not that difficult to chain the APIs used :P

**Comment by deepjyoti30** [comment]
If you end up making an app with ytmdl as dependency, do tell me, I'll add the app to my README for people to get an example that it can be used as an API ;-)
