### ISSUE TITLE
Not relevant song data search result.

### ISSUE THREAD

**Issue by orhitg** [deepjyoti30/ytmdl#45]
I was trying to download song of which I only remembered the channel name not the song name, luckily I found the song but while fetching the data about song I couldn't find the data as search results were based on the channel name that I had given for the search, instead of the song name. 

P.S: I love the tool you have developed. Specially the song data fetching.

**Comment by deepjyoti30** [comment]
Hey @orhitg Sorry for the late reply. I think you can use the ```--song``` flag to pass a song name to search for metadata.

One user faced something similar and had raised an issue and so I had added the above mentioned flag. It should probably fix your issue.

P.S: Glad you love the tool! Means a lot to me.
