### ISSUE TITLE
Gentoo packaging

### ISSUE THREAD

**Issue by xgqt** [deepjyoti30/ytmdl#47]
I have create a ebuild for ytmdl, available here:
https://gitlab.com/src_prepare/src_prepare-overlay/-/commit/4bba72c3b0b315b91fb59d814b6e8494595ab253
Would be amazing if you include this in the README.
Thanks for great software!

**Comment by deepjyoti30** [comment]
Hey @xgqt Thanks for doing that. I want to add it to the README, but since I'm not familiar with using gentoo, can you please tell me, how a user who uses gentoo is supposed to install ```ytmdl``` using the package manager?

**Comment by xgqt** [comment]
Thanks for the reply!
First the user will have to add the overlay which can be done in few ways (described in the overlay readme.md). The most common way of doing that is to use layman: `layman -a src_prepare-overlay`.
Then the user emerges ytmdl with `emerge -av --autounmask ytmdl`. `--autounmask` will make the process smoother by prompting the user to add unstable packages needed for the software to /etc/portage/package.accept_keywords (which overwrites the default behaviour of using only stable packages to satisfy dependencies)

**Comment by deepjyoti30** [comment]
@xgqt So the user will have to add your specified overlay right.

If I'm to add instructions for a gentoo user to install ytmdl it will be something like this.

1. Get the overlay from the repo you mentioned
2. Follow the instructions you just mentioned.

Is the process like above or is there a simpler way??

Also, if you want you can make a PR by updating the necessary steps required to install in Gentoo and I can merge it?!

**Comment by xgqt** [comment]
I will do a PR

**Comment by deepjyoti30** [comment]
Thanks for #48

**Comment by xgqt** [comment]
Thanks for cooperation :
)
