### ISSUE TITLE
Create config file on first run, fix issue with youtube-dl check.

### ISSUE THREAD

**Issue by deepjyoti30** [deepjyoti30/ytmdl#53]
@Tindome Please gimme some more details about the issue you faced and explain a bit about the config thing as well.

Cheers.

**Comment by deepjyoti30** [comment]
@Tindome the config setting up part is implemented and its working all right.

It would still be helpful if you could give me logs about youtube-dl check.

**Comment by Tindome** [comment]
sorry internet problems + full reinstall what i means is that on first try i must create the directory of config file,
i will retry as soon as possible and give you a complete log

**Comment by Tindome** [comment]
it works now, with --setup

**Comment by deepjyoti30** [comment]
Hey @Tindome the ```--setup``` option will be removed from the next release and a config will be created automatically. Did you try the latest commits, you would not have a ```--setup``` option.

**Comment by Tindome** [comment]
ouch my bad i'll try it
