### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by arnauldb** [deepjyoti30/ytmdl#55]
Hello,

Installed with pip on a Linux Mint Sylvia machine.
I have this error:

>  ==> Searching to see if already present in /home/arnauld/Music
>  ==> Searching Youtube for back in black
>  ==> Choose One
>  [1] AC/DC - Back In Black (Official Video) by AC/DC with dur Durée 4:15
>  [2] AC/DC - BACK IN BLACK MUSIC WITH LYRICS by Gonzalo with dur Durée 4:15
>  [3] Back In Black Full Album by Mathias Sánchez with dur Playlist
>  [4] AC/DC - Back In Black (Live At River Plate, December 2009) by AC/DC with dur Durée 4:01
>  [5] Amy Winehouse - Back To Black by Amy Winehouse with dur Durée 4:08
>  [0] More results
>  ==> Enter Choice [a valid choice] 1
>  ==> Downloading AC/DC - Back In Black (Official Video) in 320kbps
>  ==> Saving the files to: /home/arnauld/.cache/ytmdl
> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1378, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  ==> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1378, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  ==> ERROR: ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1378, in _decrypt_signature
>     video_id, player_url, s
>   File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/s/player/f676c671/player_ias.vflset/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you.

**Comment by arnauldb** [comment]
Solved by updating to the latest youtube-dl, sorry...

**Comment by deepjyoti30** [comment]
Issue fixed
