### ISSUE TITLE
Can't edit default folder

### ISSUE THREAD

**Issue by amadouderza** [deepjyoti30/ytmdl#58]
Hi,

> The defaults can be changed by editing the config file in ytmdl folder in your .config folder

I have no ytmdl folder in my /home/pi/.config folder.

Sorry if this is basic, I'm discovering linux.

**Comment by deepjyoti30** [comment]
For the current release you need to run ```ytmdl --setup``` to make the setup.

From the next release, it will be setup automatically.

**Comment by amadouderza** [comment]
Thanks!
