### ISSUE TITLE
More information on config file

### ISSUE THREAD

**Issue by johfst** [deepjyoti30/ytmdl#61]
There isn't really any information in the github readme about what the config file should be named or how it's formatted, which is making ytmdl nearly impossible to configure properly. Specifically, I'm trying to get it to download a playlist and send separate videos to separate mp3 files, rather than just dumping everything in a single mp3, and it's not working properly. But I don't know if I'm just screwing up the config file because it's not really documented.

**Comment by deepjyoti30** [comment]
Hey @johfst  Sorry for all the trouble

You can currently setup the default config by running ```ytmdl -s```.

From the next release, the config would be created automatically on the first run.

If you open the config file, you will see there are instructions on how to change the values and what values are possible.

Also you can check [this](https://github.com/deepjyoti30/ytmdl#change-defaults) section in README.

I agree that I haven't mentioned the name of the config but the location of the config is mentioned as seen [here](https://github.com/deepjyoti30/ytmdl#the-defaults-can-be-changed-by-editing-the-config-file-in-ytmdl-folder-in-your-config-folder).

I'll edit the README to add the exact name of the config along with the location.
