### ISSUE TITLE
WSL - Invalid cross-device link

### ISSUE THREAD

**Issue by bassail** [deepjyoti30/ytmdl#62]
Hello, 

I'm using Ubuntu terminal on Windows with WSL, and I am getting the following error when downloading a song : 

```
==> ERROR: [Errno 18] Invalid cross-device link: '/home/bastien/.cache/ytmdl/Bohemian Rhapsody.mp3' -> 'Bohemian Rhapsody.mp3'
```

I guess it is because of WSL and Windows.

I didn't any log file so here is what I get by enabling the DEBUG log level :

[ytmdl debug log.txt](https://github.com/deepjyoti30/ytmdl/files/4532602/ytmdl.debug.log.txt)

Hope it helps you improve ytmdl.

**Comment by deepjyoti30** [comment]
Hey @bassail Thanks for reporting the issue.

Are you able to access the ```~/.cache/ytmdl/``` directory from your terminal?? It seems like the issues is in moving the completed file from the ```.cache``` dir to the home directory.

Can you also tell me if you have put some specific directory on your config file or ytmdl is automatically moving to the default directory?

**Comment by bassail** [comment]
Found the log file under ~/.cache/ytmdl/

The mp3 files do exist under ~/.cache/ directory.

I have put a specific directory on my config file. I just `ytmdl --setup` again to get the default config file, and it works. 
I tried again with my own directory, and it works. I don't know what I did wrong.


Thanks !

**Comment by deepjyoti30** [comment]
I think the issue was probably because you've set a Windows directory as the final directory and that's why Python wasn't able to move it.

**Comment by bassail** [comment]
Just found out what was not working.

On my second attempt, I have set the following SONG_DIR path, which works fine : 
```
SONG_DIR = "/mnt/c/Users/Bastien/Music$Artist->Album->Title"
```

On my first attempt, the path was this one, which doesn't work :
```
SONG_DIR = "/mnt/c/Users/Bastien/Music$Artist->Album->[Title]"
```
and i get the error previously mentioned : 
```
==> ERROR: [Errno 18] Invalid cross-device link: '/home/bastien/.cache/ytmdl/Bohemian Rhapsody.mp3' -> 'Bohemian Rhapsody.mp3'
```

**Comment by deepjyoti30** [comment]
I think the issue was with putting those square braces around the title, probably something went wrong with that.
