### ISSUE TITLE
Problem with youtube-dl

### ISSUE THREAD

**Issue by Tindome** [deepjyoti30/ytmdl#66]
i have to disable those lines (i use virtual env) else it says youtube-dl was not detected (but i install it on the virtual env)

**Comment by deepjyoti30** [comment]
@Tindome  You mean the lines that check if youtube-dl is present, you removed those lines in order to make youtube-dl work?

**Comment by Tindome** [comment]
yes

**Comment by deepjyoti30** [comment]
Hey @Tindome Can you run ytmdl on DEBUG and gimme the logs? I tried the code on a venv and it was working all right, I need some logs to fix the bug.

**Comment by Tindome** [comment]
yes i will try as soon as i could (sorry really busy at work)
