### ISSUE TITLE
ytmdl not doing anything

### ISSUE THREAD

**Issue by mehalter** [deepjyoti30/ytmdl#7]
I am getting some strange functionality. I have done the pip install, have v0.1-r8, and have run `ytmdl -s`. It doesn't actually do anything.

If I run `ytmdl "Fractures"` for example, it completes in 1 second with no output and not files written or anything. I also get no errors, it just returns. Same if I try to pass in a URL like `ytmdl --url "https://www.youtube.com/watch?v=ZCu2gwLj9ok" "Fractures"`.

**Comment by deepjyoti30** [comment]
Are you sure no errors were shown? I tried the exact same command and its working all right. I also have v0.1-r8. Did you try with other songs.??

**Comment by mehalter** [comment]
Yup, I have also tried across distributions and multiple computers. Both Arch and Ubuntu, between 3 different computers. No error, not even an error code being sent back to the terminal. Exit status 0. Also I have tried multiple songs, with url, without, the only thing I can get it to do is setup, help, and version.

**Comment by deepjyoti30** [comment]
Can you please try the latest version?
First uninstall ytmdl by following 
```sudo pip uninstall ytmdl```
Then install it again with the following
```sudo pip install --no-cache-dir ytmdl --upgrade```
And then setup config by -s flag and try.

**Comment by mehalter** [comment]
Just did that, still nothing on all machines, its still v0.1-r8.

**Comment by deepjyoti30** [comment]
Please do the above steps again. Pypi takes a bit time. Please run the exact commands i gave you.

**Comment by mehalter** [comment]
What is the version number I am looking for so I know I have gotten the correct version?

**Comment by deepjyoti30** [comment]
Can you check the version of installed by checking the output returned by
```sudo pip install --no-cache-dir ytmdl --upgrade```
If it shows version is post9 than its r9. Also, did you try ```ytmdl -s```?

**Comment by mehalter** [comment]
Ah it does say post9 on the install but `ytmdl- -version` returns `v0.1-r8` still. Just wanted to make sure. Also Yes, I have run the commands exactly as you sent them to uninstall and reinstall, ran `ytmdl -s`, verified the config file was created, still absolutely no output or errors with and without specifying a url, on 2 laptops and a desktop, Ubuntu and Arch.

**Comment by deepjyoti30** [comment]
Clone the repo.
Then move to the dir and run following
```python ytmdl.py "Fractures"```
Please tell me if that works

**Comment by mehalter** [comment]
It does not, same behavior

**Comment by mehalter** [comment]
Ok nice, it gets to `==> Searching Youtube for Fractures`, now i get

```
Traceback (most recent call last):
  File "/home/micah/.local/lib/python3.5/site-packages/ytmdl/yt.py", line 72, in search
    data = scan_video(url)
  File "/home/micah/.local/lib/python3.5/site-packages/ytmdl/yt.py", line 89, in scan_video
    data = requests.get(search_url).json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/micah/.local/bin/ytmdl", line 168, in <module>
    main()
  File "/home/micah/.local/bin/ytmdl", line 100, in main
    data, urls = yt.search(song_name)
  File "/home/micah/.local/lib/python3.5/site-packages/ytmdl/yt.py", line 75, in search
    video.append(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by deepjyoti30** [comment]
Sorry about that. I am currently looking into that. Did you try with other song names?

**Comment by mehalter** [comment]
Yeah, I have tried multiple songs, haven't gotten anything to work.

**Comment by deepjyoti30** [comment]
Can you please try the following.
Clone the beta branch to a directory
Then run following
```python ytmdl.py "Fractures"```

**Comment by deepjyoti30** [comment]
If it prints error, please gimme the log

**Comment by mehalter** [comment]
That one seems to work

**Comment by deepjyoti30** [comment]
Everything is working??

**Comment by deepjyoti30** [comment]
Can you please try the steps again an try?? I mean clone the beta again and try. ??

**Comment by deepjyoti30** [comment]
That error should be fixed now.
Uninstall ytmdl and install it by the following commands
```sudo pip uninstall ytmdl```
```sudo pip install --no-cache-dir ytmdl --upgrade```

**Comment by mehalter** [comment]
I am getting a hang on `Downloading ....` It doesn't matter if I pass in a URL or I select one from the list, it never downloads.

**Comment by deepjyoti30** [comment]
Weird. I made some changes in downloading, that might be the issue. Anyways move to the previous version vy uninstalling and then installing post2 by following
```sudo pip install ytmdl==0.2.post2```
