### ISSUE TITLE
Pypi 3 Version Config Issues

### ISSUE THREAD

**Issue by ArcaneFuror** [deepjyoti30/ytmdl#73]
My linux distro doesn't naturally have python 2 pip for some reason, but I noticed it was available on the python 3 pip, aka pip3.

However, the documented way of generating/accessing/location of the config file is not ringing true. As both using 'ytmdl --setup' is being thrown as an unrecognized argument error by the script, and trying to navigate to ~/.config/ytmdl/config or ~/.config/ytmdl is not possible as there is no such file or directory.

Not to mention none of the options provided by the usage that shows in terminal hints at a way to generate or find the config. 

ytmdl --version returns in 2020.05.14, so seeing that it's a date format and a recent one at that, it makes me wonder if the documentation is wrong?

ytmdl -h does not display any other options for finding the configuration, and I just want to find the configuration so that I can assign it a specific location to send the downloads to.

**Comment by deepjyoti30** [comment]
@ArcaneFuror Since the May release, i:e 2020.05.14, the ```--setup``` option is not available anymore. A config will be created automatically on the first run.

Just run ytmdl once and you'll have the config file in ```~/.config/ytmdl```.

I'll update the README in case it has outdated documentation.

**Comment by ArcaneFuror** [comment]
@deepjyoti30 alrighty, thank you for the clarification, the documentation I was referring to was the github page specifically.

**Comment by deepjyoti30** [comment]
@ArcaneFuror Yep, I updated the README, added instructions on how to create the config manually.
