### ISSUE TITLE
After getting to the end of the song data results, attempting to get more results twice will result in an error

### ISSUE THREAD

**Issue by pixelomer** [deepjyoti30/ytmdl#80]
![Screenshot](https://user-images.githubusercontent.com/37103802/85786016-87094180-b732-11ea-9a93-1bb37136b63f.png)

**Comment by pixelomer** [comment]
Well, it does say "enter a valid choice", but that doesn't mean this is not an issue.

**Comment by deepjyoti30** [comment]
Should be fixed in cb1b799

**Comment by deepjyoti30** [comment]
Fixed in latest release.
