### ISSUE TITLE
Failure getting song data

### ISSUE THREAD

**Issue by jepace** [deepjyoti30/ytmdl#88]
ytmdl (July 2020) version
Using Ubuntu Linux on WSL Windows 10
Installed via pip.

Perhaps there was no song data to download, but ytmdl should handle that (more) gracefully.

Thanks!

$ ytmdl fish throwing muses
 ==> ~/Downloads/Music$Artist->Album->Title: doesn't exist.
 ==> Searching to see if already present in /home/jepace
 ==> Searching Youtube for fish throwing muses
 ==> Choose One
 [1] Throwing Muses - Fish (Official Video) by 4AD with dur 4:50
 [2] Throwing Muses - Fish (lyrics) by Lucem2 with dur 4:31
 [3] Throwing Muses - Fish by Clapham Junction with dur 4:31
 [4] Throwing Muses - Fish by panheadsforever with dur 4:49
 [5] Throwing Muses - Fish (live, june 1989) by yell0wSky with dur 4:37
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading Throwing Muses - Fish (Official Video) in 320kbps
 ==> Saving the files to: /home/jepace/.cache/ytmdl
4 MB   | 11 Mb/s || ETA: 5 s                                             |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded!
 ==> Converting to mp3...
 ==> Getting song data for fish throwing muses...
Traceback (most recent call last):
  File "/home/jepace/.local/bin/ytmdl", line 434, in <module>
    extract_data()
  File "/home/jepace/.local/bin/ytmdl", line 429, in extract_data
    main(args)
  File "/home/jepace/.local/bin/ytmdl", line 360, in main
    if len(TRACK_INFO) == 0:
TypeError: object of type 'bool' has no len()

**Comment by jepace** [comment]
Line 115 in metadata.py returns FALSE, when it should probably return an empty list?

**Comment by danimateo** [comment]
Check [my](https://github.com/deepjyoti30/ytmdl/pull/85) pull request. I fixed this and added other stuff.

**Comment by jepace** [comment]
With the hot fix, this no longer crashes.  It doesn't actually work, but it doesn't crash.  So I guess I will close it.

[...]
==> Getting song data for fish throwing muses...
 ==> Something went wrong with Gaana. The program will continue withthe other providers. Please check '/home/jepace/.cache/ytmdl/logs/log.cat' for more details.
 ==> "gaana" isn't implemented. Skipping!
 ==> No data was found!
$
