### ISSUE TITLE
Improve local search

### ISSUE THREAD

**Issue by NISH1001** [deepjyoti30/ytmdl#9]
Hi,
Thanks for mentioning me on the README.

I just went through the source code of ytmdl, especially the logic where the search is.
I saw the search module and it seems the search you are using is buggy search I had written before the improvement.
Can you look into this commit on how I have improved the local search:
https://github.com/NISH1001/playx/commit/9fd464b6849a0a4ea960d36168c861f069cfa37a

Originally, I had used Jaccard distance to try to match the total number of words that are common. But I have improved by using 2 levels of matching. Do give that commit message a read (and if possible the source code from playx).

Cheers.

**Comment by deepjyoti30** [comment]
Thanks for reminding me. I was aware of the changes but was feeling lazy. Thanks, once again!
