### ISSUE TITLE
[FEATURE] Cut song

### ISSUE THREAD

**Issue by danimateo** [deepjyoti30/ytmdl#90]
I think this would be a nice feature, because I tried using the trim option and honestly it didn't work. Don't get me wrong, it's a nice feature and worth improving upon, but for now manually specifying times seems like a nice thing to have. Also, the model used by inaSpeech is trained mostly in French and is meant more for separating male-female voices. Anyway, you said there had just been a release, so maybe we could make an experimental branch and test more stuff? Let me know your thoughts. I can make a PR just for the cut option if you make the branch.

**Comment by deepjyoti30** [comment]
@danimateo Can you tell me which songs you tried  the trim fucntionality on??

I did try it in some English as well as Hindi songs and it was working really nice, I don't know why it didn't work for you.

**Comment by danimateo** [comment]
Well, [https://youtu.be/ZGWcvJELOt4](here) is an example, also https://youtu.be/aIHF7u9Wwiw](here). Those are the only ones I can remember, but it didn't work for anything iirc.

Anyway, even if it worked for you and I picked the worst songs for this, it's not 100% reliable. Something manual would be good for the cases where this doesn't work.

**Comment by deepjyoti30** [comment]
@danimateo Okay, I'll take a look at the examples.

I have been a bit reluctant to add something like a cut feature because it's basically the same thing that ffmpeg does, you know, it's like even if we do not add that feature, a person can just use ffmpeg themselves and make the trimming.

Also, if we want to add a feature like that, we would have to consider all the aspects. We would need to consider cases where the person wants to trim out let's say some audio in two places, so that would be a bit of a hard implementation.

Also, adding two commandline options for trimming would not be a good way to go. Just like ffmpeg has it implemented, we can pass the timestamps in one arg and it will do the rest accordingly, I think that is a nice implementation.

Anyway, give it a thought. I added automatic trimming because that's something that people cannot just up and about use a library to use and make changes, however manual trimming is something that a lot of libraries offer.

**Comment by danimateo** [comment]
> I have been a bit reluctant to add something like a cut feature because it's basically the same thing that ffmpeg does, you know, it's like even if we do not add that feature, a person can just use ffmpeg themselves and make the trimming.

Well I see where you are coming from, but by that logic, meta information isn't needed either, you can just fill it with easytag and then you have yourself youtube-dl. My opinion is that it would be nice to have something like this included, it's just a wrapper for ffmpeg that's for sure, but it's a bit easier to use for this case. 

Also, I like my cli tools to be kind of a one stop thing, I want to download a song, I run this and that's it. I don't want to mess with ffmpeg afterwards as well.

It isn't a big overhead anyway, my philosophy is the more features the better (as long as it holds to the original purpose). I can understand wanting to keep it simple as well, so it's your call (arguably machine learning isn't keeping it simple, but anyway)

> Also, adding two commandline options for trimming would not be a good way to go. Just like ffmpeg has it implemented, we can pass the timestamps in one arg and it will do the rest accordingly, I think that is a nice implementation.

Actually, ffmpeg has `-ss` and `-to` options to specify start and stop. Is there something else that I'm not aware of?

**Comment by deepjyoti30** [comment]
@danimateo All right that sounds good, we can add this feature.

But before going forward we need to consider the cases. Let's say a person wants to cut out two time intervals. How would we implement something like that?

I guess having a basic command to specify start and stop is all right but what about the other cases?

**Comment by danimateo** [comment]
Well, I think that would be a too advanced use case to implement, because 99% of the time, you want to cut out start and end because there is noise you know? Otherwise, if you think this would be important, we could do comma separated arrays of start and stop. What do you think?

**Comment by deepjyoti30** [comment]
@danimateo Yeah we can have something like passing arrays with timestamps but then we would have to make other checks.

Let's go with the naive way of implementing just the start and end. Maybe we can do something like using just one option and people would be able to pass comma seperated values and we'll automatically detect which the start and what the stop is.

Share your thoughts of how you're thinking of implementing it.

**Comment by danimateo** [comment]
Well, we could do something like just `--cut 0:30 1:10 1:30 1:50` and that would mean get the intervals from 0:30 to 1:10 and 1:30 to 1:50 and then merge them and we would only need to check if they are in increasing order and even numbered. The base case would be easy like just the start and the end `--cut 0:30 1:10`. We basically need to repeat what I did in that PR with the cutting for every pair in the argument list. What do you think? Sounds easy to use, implement and pretty powerful.

**Comment by danimateo** [comment]
See #101

**Comment by deepjyoti30** [comment]
@danimateo  I will
