### ISSUE TITLE
[SUGGESTION] Choose which api providers to use in the config

### ISSUE THREAD

**Issue by danimateo** [deepjyoti30/ytmdl#91]
As the title says, I think Gaana is great if you listen to Indian music, but it's not that useful otherwise. Maybe add an option in the config to remove it? Also, maybe there will be other providers in the future added, so we can prepare for this as well. Thoughts?

**Comment by danimateo** [comment]
See the #94 PR

**Comment by jepace** [comment]
I agree with making this a tunable.  It seems incredibly unlikely that I'll ever need to use an Indian music database.

**Comment by danimateo** [comment]
Yeah I talked to @deepjyoti30  about the PR I made, it should be good to go once he looks over it and gives the green light. In the future maybe we will also add Spotify, Last FM, Deezer, etc.
