### ISSUE TITLE
EnvironmentError while Installing

### ISSUE THREAD

**Issue by Noman-Aziz** [deepjyoti30/ytmdl#95]
So i'm installing it on arch linux using
yay -S ytmdl
so after some time it gives this error

ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x55772791cb90)

I've got more than enough space in my / directory so what should i do now?

**Comment by danimateo** [comment]
Because of the tensorflow dependency I think your tmp is getting too full. Do you have a low amount of RAM? 

Try doing `export TMPDIR='/var/tmp` and see if it works.

**Comment by deepjyoti30** [comment]
@Noman-Aziz As @danimateo  said, this is probably not an issue with ytmdl itself but I do understand that ```tensorflow``` is a huge dependency, so you can consider installing ```ytmdl``` from source, just comment out the ```tensorflow``` dependency in the ```setup.py``` file.

However, without tensorflow you won't be able to use the ```--trim``` feature.

**Comment by Noman-Aziz** [comment]
> @Noman-Aziz As @danimateo said, this is probably not an issue with ytmdl itself but I do understand that `tensorflow` is a huge dependency, so you can consider installing `ytmdl` from source, just comment out the `tensorflow` dependency in the `setup.py` file.
> 
> However, without tensorflow you won't be able to use the `--trim` feature.

Yes this seemed to work, thank you!
