### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by Noman-Aziz** [deepjyoti30/ytmdl#97]
Hi, so whenever i try to download any song this error comes in the end,
e.g i write

ytmdl eminem leaving heaven

then i select the song from the list and the song gets downloaded and gets put in the .cache folder and then this error comes

 ==> Enter Choice [a valid choice] 2
 ==> Downloading Leaving Heaven (feat. Skylar Grey) [Official Audio] in 320kbps
 ==> Saving the files to: /home/naumanaziz/.cache/ytmdl
4 MB   | 1 Mb/s || ETA: 3 s                                                 |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100% ==> Downloaded!
 ==> Converting to mp3...
 ==> Getting song data for take me to heaven eminem...
Traceback (most recent call last):
  File "/home/naumanaziz/.local/bin/ytmdl", line 434, in <module>
    extract_data()
  File "/home/naumanaziz/.local/bin/ytmdl", line 429, in extract_data
    main(args)
  File "/home/naumanaziz/.local/bin/ytmdl", line 360, in main
    if len(TRACK_INFO) == 0:
TypeError: object of type 'bool' has no len()

btw, i'm using latest pop os.

**Comment by danimateo** [comment]
Made  a PR, check #99

**Comment by Noman-Aziz** [comment]
Thank You, it Worked!
