### ISSUE TITLE
Error whilw

### ISSUE THREAD

**Issue by alepando** [deepjyoti30/ytmdl#98]

**Comment by alepando** [comment]
~/ytmdl$  sudo python setup.py install
[sudo] password for alepa: 
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import setuptools
ImportError: No module named setuptools

And now try install with pip:
$  pip install ytmdl
Collecting ytmdl
  Using cached ytmdl-2020.7.9-py3-none-any.whl (32 kB)
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from ytmdl) (2.23.0)
Requirement already satisfied: mutagen in /usr/lib/python3/dist-packages (from ytmdl) (1.44.0)
Collecting inaSpeechSegmenter
  Using cached inaSpeechSegmenter-0.6.2-py3-none-any.whl (13.8 MB)
Requirement already satisfied: youtube-dl in /usr/lib/python3/dist-packages (from ytmdl) (2020.6.16.1)
Collecting downloader-cli
  Using cached downloader_cli-0.1.0.post2-py3-none-any.whl (7.8 kB)
Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (from ytmdl) (0.26)
Collecting pysocks
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from ytmdl) (0.4.3)
Collecting itunespy
  Using cached itunespy-1.6.0-py3-none-any.whl (12 kB)
Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting tensorflow
Terminado (killed)

And the installation fails too

**Comment by alepando** [comment]
And with pip3:
$ pip3 install ytmdl
Collecting ytmdl
  Using cached ytmdl-2020.7.9-py3-none-any.whl (32 kB)
Collecting pysocks
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from ytmdl) (0.4.3)
Collecting inaSpeechSegmenter
  Using cached inaSpeechSegmenter-0.6.2-py3-none-any.whl (13.8 MB)
Collecting tensorflow
Terminado (killed)

Fails too

**Comment by alepando** [comment]
The problem is with 'tensorflow' that have problem to install in debian 10.

**Comment by danimateo** [comment]
probably you're running our of memory, see #95

**Comment by alepando** [comment]
The reality is that the problem still exists in Debian tresting, debian stable, Python 2, 3 and 3.7.

**Comment by deepjyoti30** [comment]
@alepando Have you tried the newer versions where tensorflow is not installed by default and instead is optional.
